import '../model/hymn.dart';

class HymnTestLyrics {
  List<Hymn> hymnLyrics = [
    Hymn(
      id: '1',
      versesYoruba: [
        [
          "Ji okan mi, ba oorun ji ",
          "Mura si işe ojo re:",
          "Maşe ilora, ji kutu,",
          "K'o san gbese ebo oro.",
        ],
        [
          "Ogo fun Enit' o so mi.",
          "To tu mi l'ara loj' orun;",
          "Oluwa ijo mo ba sun",
          "Ji mi s'aiye ainipekun.",
        ],
        [
          "Oluwa mo tun eje je ",
          "Tu eşe ka b' iri oro",
          "So akoro nu mi oni",
          "Si f' Emi Re kun inu mi",
        ],
        [
          "Oro, at' işe mi oni",
          "Ki nwon le ri bi oko Rę",
          "K' emi si f' ipa mi gbogbo",
          "Sise re fun ogo Re",
        ],
        [
          "Ji, gbon 'ra nu, 'wo okan mi",
          "Yan ipo re l'arin Angel'",
          "Awon ti nwon nkorin lyin",
          "Ni gbogbo oru s' Oba wa.",
        ],
        [
          "Ro gbogb' ojo t'o fi sofo",
          "Bere si rere 'se loni:",
          "Kiyes' irin' re l'aiye yi:",
          "K'o si mura d' ojo nla ni.",
        ],
        [
          "Gba ninu imolę orun,",
          "Si tanmolę na f' elomi:",
          "Je ki ogo Olorun re",
          "Han n'nu iwa at' işe rę.",
        ],
        [
          "Yin Olorun ibu ore:",
          "E yin, enyin ęda aiye",
          "E yin, enyin eda orun",
          "Yin Baba, Omo on Emi.",
        ]
      ],
      versesEnglish: [
        [
          "Awake, my soul, and with the sun,",
          "Thy daily stage of duty run,",
          "Shake off dull sloth, and joyful rise;",
          "To pay thy morning sacrifice.",
        ],
        [
          "Glory to Thee who safe hast kept",
          "And hast refresh’s while I slept",
          "Grant, Loed, when I from death shall wake",
          "I may of endless light partake.",
        ],
        [
          "Lord, I ,y vows to Thee renew,",
          "Disperse my sins as morning dew;",
          "Guard first springs of though and will,",
          "And with Thyself my spirit fill.",
        ],
        [
          "Direct, control suggest this day",
          "All I design, or do, or say;",
          "That all my powers with all their might",
          "In Thy sole glory may unite.",
        ],
        [
          "Wake, and control suggest this day",
          "And with the angels bear thy part,",
          "Who all night long unwearied sing,",
          "High praise to the eternal King.",
        ],
        [
          "Thy precious time mis-spent redeem;",
          "Each present day thy last esteem;",
          "Improve thy talent with due care;",
          "For the great day, thyself prepare.",
        ],
        [
          "By influence of the light Divine",
          "Let thy own light to others shine;",
          "Reflect all heaven's propitious rays",
          "In ardent love and cheerful praise.",
        ],
        [
          "Praise God, from whom all blessing flow",
          "Praise Him, all creatures here below",
          "Praise Him, above ye Heavenly host",
          "Praise Father, Son, and Holy Ghost.",
        ]
      ],
    ),
    Hymn(id: '2', versesYoruba: [
      [
        "Oluwa mi, mo njade lo.",
        "Lati se ise ojo mi.",
        "Iwo nikan l'emi o mo.",
        "L'oro l'ero; ati n' işe.",
      ],
      [
        "Ise t'O yan mi, l' anu Re",
        "Jęki nle şe tayotayo:",
        "Ki nr' oju Re ni iSe mi,",
        "K' emi si le f' ife Re han.",
      ],
      [
        "Dabobo mi lowo 'danwo,",
        "K'o pa okan mi mo kuro",
        "L'owo aniyan aiye yi,",
        "Ati gbogbo ifękufe.",
      ],
      [
        "Iwo t' oju Re r' okan mi,",
        "Maa wa low' otun mi titi,",
        "Ki nmaa şişe lo l'ase Re.",
        "Ki nf' işe mi gbogbo fun O.",
      ],
      [
        "Je ki nreru Re t'o fuye",
        "Ki nmaa sora nigba gbogbo,",
        "Ki nma f' oju si nkan t' orun,",
        "Ki nsi mura d' ojo ogo:",
      ],
      [
        "Ohunkohun t'O fi fun mi",
        "Jeki nle lõ fun ogo",
        "Re Ki nf'ayo sure ije mi,",
        "Ki mba O rin titi d' orun.",
      ]
    ], versesEnglish: [
      [
        "Forth in Thy name, O Lord, I go",
        "My daily labour to pursue;",
        "Thee, only Thee, resolved to know,",
        "In all I think, or speak, or do.",
      ],
      [
        "The task Thy wisdom hath assign’d",
        "Oh let me cheerfully fulfill;",
        "In all my works Thy presence find,",
        "And prove Thy good and perfect will.",
      ],
      [
        "Thou be my Shield from all dangers",
        "Preserve my soul, from evil tide",
        "From anxiety of the world",
        "Also from all the lust of flesh.",
      ],
      [
        "Thee may I set at my right hand,",
        "Whose eyes my inmost substance see;",
        "And labour on at Thy command,",
        "And offer all my works to Thee.",
      ],
      [
        "Give me to bear Thy easy yoke,",
        "And every moment watch and pray;",
        "And still to things eternal look,",
        "And hasten to Thy glorious day.",
      ],
      [
        "For Thee delightfully employ",
        "Whate’er Thy bounteous grace hath given;",
        "And run my course with even joy,",
        "And closely walk with Thee to heaven.",
      ]
    ]),
    Hymn(
      id: '3',
      versesYoruba: [
        [
          "Wa s'odo mi, Oluwa mi,",
          "Ni kutukutu owuro,",
          "Mu k' ero rere so jade,",
          "Lat' inu mi soke grun.",
        ],
        [
          "Wa s' odo mi,Oluwa mi,",
          "Ni wakati osan gangan,",
          "Ki 'yonu ma ba se mi mo",
          "Nwon a si s' osan mid' oru.",
        ],
        [
          "Wa s' odo mi, Oluwa mi,",
          "Nigbati ale ba nle lo",
          "Bi okan mi ba nşako lo",
          "Muu pada, f' oju 're wo mi.",
        ],
        [
          "Wa s' odo mi, Oluwa mi.",
          "Li oru, nigbati orun",
          "Ko woju mi: je k'okan mi",
          "Ri 'simi je li aiya Re.",
        ],
        [
          "Wa s'odo mi, Oluwa mi",
          "Ni gbogbo ojo aiye mi:",
          "Nigbati emi mi ba lo.",
          "Ki nie n' tbugbe lodo Re.",
        ]
      ],
      versesEnglish: [
        [
          "Come to me, Lord, when first I wake,",
          "As the faint light of morning break;",
          "Bid purest thoughts within me rise.",
          "Like crystal dew-drops to the night.",
        ],
        [
          "Come to me in the sultry noon,",
          "Or earth’s low communing will soon",
          "Of Thy dear face eclipse the light,",
          "And change my fairest day to night.",
        ],
        [
          "Come to me in the evening shade,",
          "And, if may heart from Thee hath stray,",
          "Oh bring it back, and from afar",
          "Smile on me like Thine evening star.",
        ],
        [
          "Come to me in the midnight hour,",
          "When sleep withholds its-balmy power;",
          "Let my lone spirit find her rest,",
          "Like John, upon my Saviour’s breast.",
        ],
        [
          "Come to me through life’s varied way,",
          "And when its pulses cease to play,",
          "Then, Saviour, bid me come to Thee,",
          "That where Thou art, thy child may be.",
        ],
      ],
    ),
    Hymn(id: '4', versesYoruba: [
      [
        "Wa s'adura ooro,",
        "Kunle k'a gbadura,",
        "Adura ni opa Kristian,",
        "Lati b' Olorun rin.",
      ],
      [
        "Losan, wolę labe",
        "Apat' aiyeraiye,",
        "Itura ojiji Rę dun",
        "Nigbat' orun ba mu.",
      ],
      [
        "Je ki gbogbo ile",
        "Wa gba 'dura l' ale,",
        "Ki ile wa di t' Olorun",
        "Ati 'bode run.",
      ],
      [
        "Nigbat' o d'oganjo",
        "Je k'a wi l'emi, pe",
        "Mo sun sugbon okan mi ji",
        "Lati ba O sona",
      ]
    ], versesEnglish: [
      [
        "Come to the morning prayer;",
        "Come let us kneel and pray,",
        "Prayer is the Christian pilgrim’s staff",
        "To walk with God all day.",
      ],
      [
        "At noon beneath the Rock",
        "Of Ages rest and pray;",
        "Sweet is the shadow from the heat,",
        "When the sun smites by day.",
      ],
      [
        "At eve shut to the door,",
        "Round the home-alter pray,",
        "And finding there the house of God,",
        "At heaven’s gages close the day.",
      ],
      [
        "When midnight seals our eyes,",
        "Let each in spirit say,",
        "I sleep, but my heart waketh, Lord,",
        "With Thee to watch and pray.",
      ]
    ]),
    Hymn(
      id: '5',
      versesYoruba: [
        [
          "Imole ooro didun yi",
          "Ji mi nin' orun mi",
          "Baba, ife Tire nikan",
          "L'o pa omo Rę mo.",
        ],
        [
          "Ni gbogbo oni, mo bę O.",
          "Maa şe Oluso mi.",
          "Dariji mi, Jesu mimo",
          "Ki 'm je Tire loni.",
        ],
        [
          "Wa şe 'bugbe Rę ninu mi,",
          "Emi ore-ofę!",
          "So mi di mimo laiye yi,",
          "K' emi le r' oju Re.",
        ],
      ],
      versesEnglish: [
        [
          "The morning bright with rosy light",
          "Has waked me from my sleep;",
          "Father, I own Thy love alone",
          "Thy little one doth keep.",
        ],
        [
          "All through the day, I humbly pray,",
          "Be Thou my guard and guide;",
          "My sins forgive, and let me live,",
          "Lord Jesus, near Thy side.",
        ],
        [
          "Oh make Thy rest within mu breast,",
          "Great Spirit of all grace;",
          "Make me like Thee, then shall I be",
          "Prepared to see Thy face.",
        ]
      ],
    ),
    Hymn(id: '6', versesYoruba: [
      [
        "Baba mi, gbo t' emi",
        "Wo ni Alaabo mi",
        "Maa sunmo mi titi,",
        "Oninure julo.",
      ],
      [
        "Jesu, Oluwa mi,",
        "Iye at' ogo mi",
        "Ki 'gba na yara de,",
        "Ti ngo de odo Re.",
      ],
      [
        "Olutunu julo,",
        "'Wo ti ngbe inu mi,",
        "'Wo t'o mo aini mi,",
        "Fa mi, k' o si gba mi",
      ],
      [
        "Mimo, Mimo, Mimo",
        "Má fi mi silę lai",
        "Se mi n'ibugbe Re",
        "Tire nikan lailai.",
      ],
    ], versesEnglish: [
      [
        "Holy Father, hear me;",
        "Thou art my Defender:",
        "Be thou ever near me,",
        "Loving, true, and tender.",
      ],
      [
        "Jesus, blessed Master",
        "Lord of Life and glory,",
        "Bid the hours fly faster,",
        "Till I kneel before Thee.",
      ],
      [
        "Comforter  benignest,",
        "Who abiding in me",
        "All my need divinest,",
        "Move me draw me, win me.",
      ],
      [
        "Holy, Holy, Holy,",
        "Come and leave me never,",
        "Thine abode most lowly,",
        "Only Thine for ever."
      ]
    ]),
    Hymn(id: '7', versesYoruba: [
      [
        "Ninu gbogbo ewu oru,",
        "Oluwa l'o so mi:",
        "A wa si tun ri 'mole yi",
        "A tun tę ekun ba.",
      ],
      [
        "Oluwa, pa wa mo loni,",
        "Fi apa Re so wa:",
        "Kiki awon ti Wo pamo.",
        "L'o nyo ninu ewu.",
      ],
      [
        "K'oro wa ati iwa wa",
        "Wipe Tire l' awa:",
        "Tobę t' imolę otito",
        "Le tan loju aiye.",
      ],
      [
        "Má je k'a pada lodo Re",
        "Olugbala owon:",
        "Titi a o f' oju wa ri",
        "Oju re li opin.",
      ],
    ], versesEnglish: [
      [
        "From all the dangers of the night,",
        "Jesus my Lord protects,",
        "‘Am privileged to see this light",
        "I kneel to worship Thee.",
      ],
      [
        "Jesus my Lord keep me today,",
        "Protect me in Thy hands;",
        "It is only those Thou keepest",
        "That are safe from danger.",
      ],
      [
        "Let my speech and my behavior",
        "Depict that I am Thine,",
        "So much that Thy great light of truth",
        "May shine thro’ out the earth.",
      ],
      [
        "O let me not depart from Thee",
        "Thou o my Saviour dear",
        "Until I see with mine own eyes ",
        "Thy glorious face at last.",
      ]
    ]),
    Hymn(id: '8', versesYoruba: [
      [
        "Krist, Ologo, Olola,",
        "Iwo Imole aiye,",
        "Orun ododo, dide,",
        "K'o si bori okunkun;",
        "'Molę oro, sun-mo mi",
        "'Rawo oro, w' aiya mi",
      ],
      [
        "Okukun l' owuro je",
        "B' Iwo ko pelu rę wa :",
        "Ailayo l' ojo yi je.",
        "B'anu ko tan 'molę mi",
        "Fun mi n' imolę Jesu.",
        "M' okan mi gbogbo gbona:",
      ],
      [
        "Wa bę okan mi yi wo,",
        "Le okunkun se lo:",
        "F' imole orun kun mi,",
        "Si tu aigbagbo mi ka.",
        "Mã f' ara Re han mi si,",
        "Si ma ràn b' osangangan.",
      ],
    ], versesEnglish: [
      [
        "CHRIST, whose glory fills the skies,",
        "Christ, the true, the only Light,",
        "Sun of righteousness, arise,",
        "Triumph o’er the shades of night;",
        "Day-spring from on high, be near;",
        "Day star, in my heart appear.",
      ],
      [
        "Dark and cheerless is the morn,",
        "Unaccompanied by Thee;",
        "Joyless is the day’s return,",
        "Till Thy mercy’s beams I see;",
        "Till they inward light impart,",
        "Glad my eyes, and warm my heart.",
      ],
      [
        "Visit then this soul of mine",
        "Pierce the gloom of sin and grief;",
        "Fill me, Radiancy divine;",
        "Scatter all my unbelief;",
        "More and More Thyself display ",
        "Shining to the perfect day."
      ],
    ]),
    Hymn(id: '9', versesYoruba: [
      [
        "Jesu, Oorun ododo,",
        "Iwo imolę ife.",
        "Gbati 'mole owuro",
        "Ba nt' ila orun tan wa,",
        "Tan mole ododo Re",
        "Yi wa ka.",
      ],
      [
        "Gege bi iri ti nse",
        "Sori eweko gbogbo,",
        "K' Emi ore-ofe Re",
        "So okan wa di otun:",
        "Ro ojo ibukun Re",
        "Sori wa.",
      ],
      [
        "B' imole oorun ti nran,",
        "K' imolę ife Tire.",
        "Si må gbona l' okan wa,",
        "K'o si mu wa l' ara ya,",
        "K'a le ma f' ayo sin O",
        "Laiye wa.",
      ],
      [
        "Amona, ireti wa,",
        "Ma fi wa silę titi,",
        "Fi wa s' abe iso Re.",
        "Titi opin aiye wa",
        "Sin wa la a jo wa ja",
        "S'ile wa.",
      ],
      [
        "Pa wa mo n'nu ifę Rę",
        "L'ojo aiye wa gbogbo,",
        "Si mu wa bori iku,",
        "Mu wa de 'le ayo na,",
        "K'a le ba 'won mimo gba",
        "Isimi",
      ],
    ], versesEnglish: [
      [
        "JESUS, Sun of righteousness,",
        "Brightest beam of love divine,",
        "With the early morning rays,",
        "Do Thou on our darkness shine,",
        "And dispel with purest light.",
        "All our night.",
      ],
      [
        "As on drooping herb and flower",
        "Falls the soft refreshing dew,",
        "Let Thy Spirit’s grace and power ",
        "All our weary souls renew;",
        "Showers of blessing over all ",
        "Soft fall.",
      ],
      [
        "Like the sun’s reviving ray,",
        "May Thy love with tender glow",
        "All our coldness melt away,",
        "Warm and cheer us forth to go,",
        "Gladly serve Thee and obey.",
        "All the day",
      ],
      [
        "Oh, our only Hope and Guide",
        "Never leave us nor forsake;",
        "Keep us ever at Thy side",
        "Till the eternal morning break",
        "Moving on to Zion’s hill",
        "Homeward still.",
      ],
      [
        "Lead us all our days and years ",
        "In Thy strait and narrow way’",
        "Lead us through the vale of tears",
        "To the land of perfect day,",
        "Where Thy people, full blest,",
        "Safely rest.",
      ],
    ]),
    Hymn(id: '10', versesYoruba: [
      [
        "Ogo f'Olorun l'ale yi",
        "Fun gbogbo ōre imole",
        "So mi Oba awon oba",
        "L'abe ofiji iye Re.",
      ],
      [
        "Oluwa, f' eşe mi ji mi,",
        "Nitori Omo Re loni:",
        "K' emi le wa l' alafia",
        "Pelu Iwo ati aiye.",
      ],
      [
        "Jek' okan mi le sun le O.",
        "K' orun didun p' oju mi de",
        "Orun ti y'o m'ara mi le",
        "Ki nle sin O li owuro.",
      ],
      [
        "Bi mo ba dubulę laisun,",
        "F' ero orun kun okan mi,",
        "Maję ki nlala buburu",
        "Maję  k' ipa okun bo mi.",
      ],
      [
        "Yin Oluwa, gbogbo eda,",
        "Ti mbę nisalę aiye yi :",
        "E yin loke, eda orun",
        "Yin Baba, Omo, on Emi.",
      ],
    ], versesEnglish: [
      [
        "Glory Thee, my God, this night,",
        "For all the blessings of the light;",
        "Keep me, oh keep me, king of kings,",
        "Beneath Thine own Almighty wings.",
      ],
      [
        "Forgive me, Lord, for Thy dear Son,",
        "The ill that I this day have done",
        "That with the world, myself, and Thee,",
        "I, ere I sleep, at peace may be.",
      ],
      [
        "Oh may my soul on Thee repose,",
        "And may sweet sleep mine eyelids close,",
        "Sleep that shall me more vigorous make,",
        "To serve my God when I awake.",
      ],
      [
        "When in the night I sleepless lie,",
        "My soul with heavenly thoughts supply;",
        "Let no ill dreams disturb my rest,",
        "Nor powers of darkness me molest.",
      ],
      [
        "Praise God, from whom all blessings flow;",
        "Praise Him, all creatures here below;",
        "Praise Him above, ye heavenly host;",
        "Praise Father, Son and Holy Ghost.",
      ],
    ]),
    Hymn(id: '11', versesYoruba: [
      [
        "Ife Re da wa si l'oni",
        "L'are a si dubulę,",
        "Mã so wa ni'dakę oru,",
        "K'ota ma yo wa l'enu:",
        "Jesu, şe olutoju wa,",
        "Iwo l' o dun gbekele.",
      ],
      [
        "Ero at' alejo l' aiye,",
        "A ngb' arin awon ota",
        "Yo wa, at' ile wa l' ewu,",
        "L'apa Re ni k' a sun si;",
        "N' ijo iyonu aiye pin,",
        "K' a le simi l'odo Re.",
      ]
    ], versesEnglish: [
      [
        "Thy love has spared our lives to-day",
        "Weary we are kneeling down,",
        "Guide us throughout the still of night"
            "Let our foes disturb us not;",
        "Jesus guide and take care of us",
        "It is sweet to trust inThee.",
      ],
      [
        "Pilgrims and strangers in this world",
        "Amongst foes we are living",
        "Save us, for we are in danger,",
        "In Thy laps o we shall sleep;",
        "When earthly sorrows are ended,",
        "O let us all rest in Thee. "
      ],
    ]),
    Hymn(id: '12', versesYoruba: [
      [
        "Wa ba mi gbe ale fere le tan:",
        "Okunkun nşu; Oluwa, ba mi gbe;",
        "Bi oluranlowo miran ba ye",
        "Iranwo alaini, wa ba mi gbe.",
      ],
      [
        "Ojo aiye mi nsare lo s' opin,",
        "Ayo aiye nku, ogo re nwomi,",
        "Ayida at' iba je ni mo nri,",
        "'Wo ti ki yipada wa ba mi gbe.",
      ],
      [
        "Má wa l' eru b' Oba awon oba",
        "Sugbon ki o mã bo b' oninure,",
        "Ki o si ma kanu fun egbe mi",
        "Wa Ore elese, wa ba mi gbe.",
      ],
      [
        "Mo nfe O ri, ni wakati gbogbo :",
        "Ki lo le segun eşu b' ore Re?",
        "Tal' o le șe amona mi bi Rę?",
        "N'nu 'banuje at' ayo ba mi gbe.",
      ],
      [
        "Pelu 'bukun Re, eru ko ba mi,",
        "Ibi ko wuwo, ękun ko koro,",
        "Oro iku da? 'Şegun isa da?",
        "Ngo segun sibę bi 'Wo ba mi gbe.",
      ],
      [
        "Wa ba mi gbe ni wakati sisun",
        "Şe' molę mi, si toka si orun",
        "B' aiye ti nkoja, k' ilę orun mo",
        "Ni yiye, ni sisun, wa ba mi gbe."
      ],
    ], versesEnglish: [
      [
        "Abide with me; fast falls the eventide;",
        "The darkness deepens; Lord, with me abide;",
        "When other helpers fail, and comforts flee,",
        "Help of the helpless, oh, abide with me.",
      ],
      [
        "Swift to its close ebbs out life’s little day;",
        "Earth’s joy grow dim, its glories pass away",
        "Change and decay in all around I see;",
        "O Thou, who changest not, abide with me",
      ],
      [
        "Come not in terrors, as the King of kings;",
        "But kind and good, with healing in Thy wings",
        "Tears for all woes, a heart for every plea;",
        "Come, Friend of sinners, thus abide with me.",
      ],
      [
        "I need Thy presence every passing hour;",
        "What but Thy grace can foil the tempters power?",
        "Who like Thyself my guide and stay can be?",
        "Through cloud and sunshine, oh, abide with me",
      ],
      [
        "I fear no foe, with Thee at hand to bless;",
        "Ills have now eight, and tears no bitterness;",
        "Where is death’s sting? Where, grave Thy victory?",
        "I triumph still, if Thou abide with me.",
      ],
      [
        "Hold Thou Thy cross before my closing eyes;",
        "Shine through the gloom, and point me to the skies;",
        "Heaven’s morning breaks, and earth’s vain shadows flee;",
        "In life, in death, O Lord, abide with me. ",
      ],
    ]),
    Hymn(id: '13', versesYoruba: [
      [
        "Iwo Imole okan mi,",
        "Li odo Rę oru ko si,",
        "Ki kuku aiye ma bo O,",
        "Kuro l'oju iranşe Rę.",
      ],
      [
        "Nigbat' oorun alę didun",
        "Ba npa ipenpeju mi de,",
        "K' ero mi je lati simi",
        "Lai l' aiya Olugbala mi.",
      ],
      [
        "Ba mi gbe l' oro tit' ale",
        "Laisi Re emi ko le wa,",
        "Ba mi gbe gbat' ile ba nşu,",
        "Laisi Re emi ko le sun.",
      ],
      [
        "B otoşi omo Re kan",
        "Bu tapa s' oro Re loni,",
        "Oluwa şişe ore Re.",
        "Ma je k'o sun ninu eşę.",
      ],
      [
        "Bukun fun awon alaisan,",
        "Pese fun awon talaka,",
        "K' orun alawè l' ale yi,",
        "Dabi orun omo titun.",
      ],
      [
        "Sure fun wa nigbat' a ji",
        "K'a to m' ohun aiye yi şe",
        "Titi awa o de b' ifę",
        "T'a o st de ijoba Rę.",
      ]
    ], versesEnglish: [
      [
        "Sun of my soul, Thou Saviour dear,",
        "It is not night if thou be near;",
        "Oh may no earth-born cloud arise,",
        "To hide Thee from Thy servant’s eyes.",
      ],
      [
        "When the soft dews of kindly sleep",
        "My wearied eyelids gently steep",
        "Be my last thought, how sweet to rest",
        "For ever on my Saviour’s breast.",
      ],
      [
        "Abide with me from morn till eve,",
        "For without Thee I cannot live;",
        "Abide with me when night is nigh,",
        "For without thee I dare not die",
      ],
      [
        "If some poor wandering child of Thine",
        "Have spurn’d to day the voice divine",
        "Now, Lord, the gracious work begin;",
        "Let him to more lie down in sin.",
      ],
      [
        "Watch by the sick, earth the poor",
        "With blessings from boundless store;",
        "Be every mourner’s sleep to-night,",
        "Like infant’s slumbers, pure and light.",
      ],
      [
        "Come near and bless us when we wake,",
        "Ere through the world our way we take,",
        "Till in the ocean of Thy love",
        "We lose ourselves in heaven above. ",
      ],
    ]),
    Hymn(id: '14', versesYoruba: [
      [
        "L'oju ale 'gbat' orun wo,",
        "Nwon gbe abirun w' odo Rę,",
        "Oniruru ni aisan won",
        "Sugbon nwon f' ayo lo 'le won.",
      ],
      [
        "Jesu a de loj ale yi",
        "A sunmo O. t' awa t' arun wa,",
        "Bi a ko tilę le ri O",
        "Sugbon a mo p'O sunmo wa.",
      ],
      [
        "Olugbala, wo oşi wa,",
        "Omi ko san, mi 'banuje.",
        "Omi ko ni ife si O.",
        "Ife elomi si tutu.",
      ],
      [
        "Omi mo pe asan l' aiye",
        "Beni nwon ko f' aiye sile,",
        "Omi l' orę ti ko se 're,",
        "Beni nwon ko fi O ş' ore.",
      ],
      [
        "Ko s' okan ninu wa to pe",
        "Gbogbo wa si ni eleşe,",
        "Awon t'o si nsin O toto",
        "Mo ara won ni alaipe.",
      ],
      [
        "Sugbon Jesu Olugbala,",
        "Eni bi awa ni 'Wo şe,",
        "'Wo ti ri 'danwo bi awa,",
        "'Wo si ti mo ailera wa.",
      ],
      [
        "Agbar' owo Re wa sibę,",
        "Ore Re si ni agbara,",
        "Gbo adura alę wa yi",
        "Ni anu, wo gbogbo wa san."
      ]
    ], versesEnglish: [
      [
        "At even, ere the sun was set,",
        "The sick, O Lord around Thee lay;",
        "Oh, in what divers pains they met!",
        "Oh, with what joy they went away!",
      ],
      [
        "Once more ‘tis eventide, and we,",
        "Oppress’d with various ill; draw near;",
        "What if Thy form we cannot see?",
        "We know and feel that Thou are here.",
      ],
      [
        "O Saviour Christ, Our woes dispel;",
        "For some are sick, and some are sad,",
        "And some have never loved Thee well,",
        "And some have lost the love they had;",
      ],
      [
        "And some have found the world is vain,",
        "Yet from the world they break not free;",
        "And some have friends who give them pain,",
        "Yet have not sought a friends in Thee.",
      ],
      [
        "And none, O Lord, have perfect rest,",
        "For none are wholly free from sin;",
        "And they, who fain would serve Thee best,",
        "Are conscious most of wrong within.",
      ],
      [
        "O Saviour Christ, Thou too art Man;",
        "Thou hast been troubled, tempted, tried",
        "Thy kind but searching glance can scan",
        "The very wounds that shame would hide.",
      ],
      [
        "Thy touch has still its ancient power;",
        "No word from Thee can fruitless fall;",
        "Hear in this solemn evening hour.",
        "And in Thy mercy heal us all. ",
      ],
    ]),
    Hymn(id: '15', versesYoruba: [
      [
        "'Wo imole larin ookun aiye,",
        "Må sin mi lo.",
        "Okunkun şu, mo si jina sile",
        "Má sin mi lo.",
        "To 'şisę mi: ohun ehin ola",
        "'Mi ko bere: şişe kan to fun mi.",
      ],
      [
        "Nigbakan ri, emi ko bę O pe",
        "Mã sin mi lo:",
        "Bę ni nko fę O: sugbon nigbayi",
        "Mã sin mi lo:",
        "Afę aiye ni mo ti nto le-hin",
        "Sugbon Jesu, má ranti igbani."
      ],
      [
        "Ipa Re l'o ti ndi mi mu, y' o si",
        "Mã sin mi lọ:",
        "Ninu erę ati yangi aiye,",
        "Mã sin mi lo",
        "Titi em' o fi ri awon wonni",
        "Ti mo fe, ti nwon ti f' aiye silę.",
      ]
    ], versesEnglish: [
      [
        "LEAD, kindly light, amid the encircling gloom",
        "Lead Thou me on.",
        "The night is dark, and I am far from home:",
        "Lead Thou me on.",
        "Keep Thou my feet; I do not ask to see",
        "The distant scene, one step enough for me.",
      ],
      [
        "I was not ever thus, nor pray’d that Thou ",
        "Shouldst lead me on;",
        "I loved to choose and see my path; but now",
        "Lead Thou me on.",
        "I love the garish day, and spite of fears",
        "Pride ruled my will, remember not past years.",
      ],
      [
        "So long Thy power hath blest me, sure it still",
        "Will lead me on",
        "O’er moor and fen, o’er crag and torrent, till",
        "The night is gone.",
        "And with the morn those angel faces smile",
        "Which I have loved long since, and lost awhile. ",
      ],
    ]),
    Hymn(id: '16', versesYoruba: [
      [
        "Jesu, bukun wa k'a to lo:",
        "Gbin oro Re si aiya wa,",
        "K'o si mu k' ife gbigbona",
        "Kun okan ilowowo wa",
        "Nigba iye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
      [
        "llę ti şu orun ti wo",
        "Wo si ti şiro iwa wa",
        "Die n' isegun wa loni",
        "Işubu wa l' o papoju:",
        "Nigba lye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
      [
        "Jesu, dariji wa; fun wa",
        "L'ayo ati eru mimo,",
        "At' okan ti ko l' abawon",
        "K'a ba le jo O l'ajotan:",
        "Nigba ye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
      [
        "Lala dun, tori 'Wo se ri;",
        "Aniyan ferę. O se ri.",
        "Ma je k'a gbo t' ara nikan",
        "K'a ma bo sinu idewo,",
        "Nigba iye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
      [
        "A mbę O f' awon alaini,",
        "Felese at' awon t' a fe.",
        "Je ki anu Re mu wa yo,",
        "'Wo Jesu, l' ohun gbogbo wa,",
        "Nigba iye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
      [
        "Jesu bukun wa ile şu,",
        "Tikalarę wa ba wa gbe,",
        "Angel' rere nşo ile wa,",
        "A tun f' ojo kan sunmo O.",
        "Nigba iye at' iku wa,",
        "Jesu jare, se 'molę wa.",
      ],
    ], versesEnglish: [
      [
        "O SAVIOUR, bless us ere we go,",
        "Thy word into our minds instill,",
        "And make our lukewarm hearts to glow",
        "With lowly love and fervent will.",
        "Through life’s long day and death’s dark night",
        "O gentle Jesus, be our light.",
      ],
      [
        "The day is gone, its hours have run;",
        "And Thou hast taken count of all,",
        "The scanty triumphs grace hath won,",
        "The broken vow, the frequent fall.",
        "Through life’s long day and death’s dark night",
        "O gentle Jesus, be our light.",
      ],
      [
        "Forgive us, Lord; yea, give us joy,",
        "Sweet fear, and sober liberty,",
        "And loving hearts without alloy",
        "That only long to be like Thee.",
        "Through life’s long day and death’s dark night",
        "O gentle Jesus, be our light.",
      ],
      [
        "Labour is sweet, for Thou hast toil’d",
        "And care is light, for Thou has cared:",
        "Let not our works with self be soil’d",
        "Nor in unsimple ways ensnared.",
        "Through life’s long day and death’s dark night",
        "O gentle Jesus, be our light.",
      ],
      [
        "For all we love, the poor the sad,",
        "The sinful, unto Thee we call;",
        "Oh let Thy mercy make us glad",
        "Thou art our Saviour, and our all.",
        "Through life’s long day and death’s dark night",
        "O gentle Jesus, be our light.",
      ],
      [
        "O Saviour, bless us; night is come;",
        "Thy holy Presence with us be.",
        "Good angels watch about our home,",
        "And we are one day nearer Thee;",
        "Through life’s long day, and death’s dark night,",
        "O gentle Jesus, be our light. ",
      ]
    ]),
    Hymn(id: '17', versesYoruba: [
      [
        "K'a to sun Olugbala wa,",
        "Fun wa n' ibukun alę :",
        "A jewo ese wa fun O,",
        "Iwo lo le gba wa la.",
      ],
      [
        "B' ile tile ti şu dudu,",
        "Ökün ko le se wa mo:",
        "Iwo eniti ki şarę",
        "Nso awon enia Re.",
      ],
      [
        "B'okunkun tile yi wa ka",
        "Ti ofa nfo wa koja,",
        "Awon Angeli yi wa ka,",
        "Awa o wa l' ailewu,",
      ],
      [
        "Nirelę awa f'ara wa",
        "S'abę abo Re, Baba,",
        "Jesu, Wo t' o sun bi awa,',",
        "Şe orun wa bi Tirę.",
      ],
      [
        "Emi Mimo rado bo wa,",
        "Tan 'molę s' okunkun wa",
        "Tit' awa o fi ri ojo",
        "Imolę aiyeraiye.",
      ],
    ], versesEnglish: [
      [
        "Father, breathe an evening blessing,",
        "Ere repose our spirits seal;",
        "Sin and want we come confessing,",
        "Thou canst save, and Thou canst heal.",
      ],
      [
        "Though the night be dark and dreary",
        "Darkness cannot hide from Thee;",
        "Thou art He, who never weary",
        ",Watchest where Thy people be.",
      ],
      [
        "Though thick-darkness walk around us,",
        "Though the arrow past us fly,",
        "Angel-guards from Thee surround us",
        "We are safe, if Thou art nigh.",
      ],
      [
        "Father to thy holy keeping",
        "Humbly we ourselves resign;",
        "Saviour, who has slept our sleeping",
        "Make our slumbers pure as Thine.",
      ],
      [
        "Blessed Spirit, brooding o’er us,",
        "Chase the darkness of our night,",
        "Till the perfect day before us ",
        "Breaks in everlasting light. ",
      ],
    ]),
    Hymn(id: '18', versesYoruba: [
      [
        "Oluwa ojo yi ti d'opin",
        "Okunkun si de l' aşe Re",
        "'Wo l' a korin owuro wa si,",
        "Iyin Re y'o m' ale wa dun.",
      ],
      [
        "A dupę ti ijo Rę ko nsun,",
        "B' aiye ti nyi lo s'imole",
        "O si nşona ni gbogbo aiye,",
        "Ko si simi tosan-toru.",
      ],
      [
        "B' ile si ti nmo lo jojumo",
        "Ni orile at' ekuşu,",
        "Ohun adura ko dakę ri,",
        "Bę l' orin iyin ko dekun.",
      ],
      [
        "Oorùn t'o wo fun wa, si ti la",
        "S' awon eda iwo-oorùn,",
        "Nigbakugba li enu si nso",
        "Işe 'yanu Re di mimo.",
      ],
      [
        "Be, Oluwa, lai n' ijoba Re:",
        "Ko dabi ijoba aiye;",
        "O duro, O si nşe akoso",
        "Tit' eda Rę o juba Rę.'",
      ],
    ], versesEnglish: [
      [
        "Our gracious Lord, today is ended",
        "The darkness falls at Thy behest;",
        "To Thee our morning hymns ascended,",
        "Thy praise shall hallow now our rest.",
      ],
      [
        "We thank Thee that Thy Church",
        "Unsleeping,",
        "While earth rolls onward into light.",
        "Through all the world her watch is keeping",
        "And rests not now by day or night",
      ],
      [
        "As o’er each continent and island",
        "The dawn leads on another day,",
        "The voice of prayer is never silent,",
        "Nor dies that strain of praise away",
      ],
      [
        "The sun, that bids us rest, is waking",
        "Our brethren ‘neath the western sky,",
        "And hour by hour fresh lips are making",
        "Thy wondrous doings heard on high.",
      ],
      [
        "So be it, Lord; Thy throne shall never,",
        "Like earth’s proud empires, pass away;",
        "But stand, and rule, and grow for, ever,",
        "Till all Thy creatures own Thy sway. ",
      ],
    ]),
    Hymn(id: '19', versesYoruba: [
      [
        "Baba, a tun pade l'ooko Jesu,",
        "A si wa teriba lab' ese Re",
        "A tun fe gb' ohun wa soke, si O.",
        "Lati wa anu, lati korin 'yin.",
      ],
      [
        "A yin O fun itoju 'gbagbogbo",
        "Ojojumo l'a o ma rohin 'se Rę",
        "Wiwa laye wa, anu Re ha ko?",
        "Apa Re, ki O fi ngba ni mo'ra?",
      ],
      [
        "O şel a ko ye fun ie nla Rę",
        "A şako kuro lodo Rę poju,",
        "Sugbon kikankikan ni O si npe,",
        "Nje, a de, a pada wa 'le Baba.",
      ],
      [
        "Nipa ooko t'o bor' ohun gbogbo",
        "Nipa ife t'o ta fe gbogbo yo.",
        "Nipa eje ti a ta fun ese.",
        "Şilekun anu, si gbani si 'le.",
      ]
    ], versesEnglish: [
      [
        "FATHER, again in Jesus’ name we meet,",
        "And bow in penitence beneath Thy feet;",
        "Again to Thee our feeble  voice raise,",
        "To sue for mercy, and to sing Thy praise.",
      ],
      [
        "Oh we would bless Thee for Thy ceaseless care,",
        "And all Thy work from day to day declare;",
        "Is not our life with hourly mercies crown’d?",
        "Does not Thine arm encircle us around?",
      ],
      [
        "Alas! Unworthy of Thy boundless love,",
        "Too oft with careless feet from Thee we rove;",
        "But now, encouraged by Thy voice, we come,",
        "Returning sinners to a Father’s home.",
      ],
      [
        "Oh by that name in whom all fullness dwells,",
        "Oh by that love which every love excels,",
        "Oh by that blood so freely shed for sin,",
        "Open blest mercy’s gate, and take us in.",
      ],
    ]),
    Hymn(id: '20', versesYoruba: [
      [
        "A gboju s' oke si O.",
        "At' owo, ati okan",
        "Tewogba adura wa,",
        "B'o tile se ailera",
      ],
      [
        "Oluwa je k'a mo O.",
        "Je k'a mo oruko Rę",
        "Je k' awa şe ife Re'",
        "Bi wọn ti nşe li orun.",
      ],
      [
        "Nigbati a sun loru,",
        "So wa, k'o duro ti wa;",
        "Nigbati ile si mo,',",
        "K'a ji, k'a f' iyin fun O.",
      ],
    ], versesEnglish: [
      [
        "We lift our eyes up to Thee,",
        "With our hands and all our minds:",
        "Accept then all our prayers",
        "Although they may not be strong.",
      ],
      [
        "O Lord let us know Thy self,",
        "O let us know Thy good name,",
        "And let us Thy will perform",
        "Just as they do in heaven.",
      ],
      [
        "O Lord, when we sleep at night,",
        "Please keep us and stand by us;",
        "Also when the day light breaks,",
        "Awakened, let us praise Thee.",
      ],
    ]),
    Hymn(
      id: '21',
      versesYoruba: [
        [
          "Ojo oni lo tan,",
          "Oru sunmole:",
          "Okunkun ti de na,",
          "Ilę si ti şu."
        ],
        [
          "Okunkun bo ilę.",
          "Awon 'rawo yo:",
          "Eranko at' eiye.",
          "Lo si 'busun won.",
        ],
        [
          "Jesu f' orun didun",
          "F' eni alare:",
          "Je ki ibukun Re",
          "Pa oju mi de.",
        ],
        [
          "Je k' omo kekere",
          "La ala rere;",
          "Ş' oloko t' ewu nwu",
          "Ni oju omi.",
        ],
        [
          "Mã toju alaisan",
          "Ti ko r' orun sun;",
          "Awon ti nro ibi,",
          "Jo da won l' ekun.",
        ],
        [
          "Ninu gbogbo oru,",
          "Je k' angeli Rę",
          "Mã şe oluşo mi,",
          "L'ori 'busun mi",
        ],
        [
          "'Gbat' ile ba si mo",
          "Je k' emi dide; ",
          "B' omo ti ko l' ese",
          "Ni iwaju Rę.",
        ],
        [
          "Ogo ni fun Baba,",
          "Ati fun Omo,",
          "Ati f' Emi Mimo,",
          "Lai ati lailai.",
        ],
      ],
      versesEnglish: [
        [
          "Now the day is over,",
          "Night is drawing nigh,",
          "Shadows of the evening",
          "Steal across the sky.",
        ],
        [
          "Now the darkness gathers,",
          "Stars their watches keep,",
          "Birds, and beasts, and flowers",
          "Soon will be asleep.",
        ],
        [
          "Jesus give the weary",
          "Calm and sweet repose;",
          "With Thy tenderest blessing",
          "May mine eyelids close.",
        ],
        [
          "Grant to little children",
          "Visions bright of Thee;",
          "Guard the sailors tossing",
          "On the deep blue sea.",
        ],
        [
          "Comfort every sufferer",
          "Watching late in pain;",
          "Those who plan some evil",
          "From their sin restrain.",
        ],
        [
          "Through the long night watches",
          "May Thine angels spread",
          "Their white wings above me,",
          "Watching round my bed.",
        ],
        [
          "When the morning wakens,",
          "Then may I arise",
          "Pure, and fresh, and sinless",
          "In thy holy eyes.",
        ],
        [
          "Glory to the father,",
          "Glory to the Son,",
          "And to Thee, blest Spirit,",
          "Whilst all ages run."
        ],
      ],
    ),
    Hymn(id: '22', versesYoruba: [
      [
        "Ojo oni koja lo;",
        "A dupę, Oluwa;",
        "Jo gba wa lowo ese",
        "Ni wakati oru:",
        "Jesu jo f' iso Re so wa, ",
        "Si mu wa la oru yi ja.",
      ],
      [
        "Ayo oni koja lo:",
        "A gb' okan wa soke",
        "Jo, má je k'a n' ikose",
        "Ni wakati oru:",
        "Jesu, jo fun wa ni 'molę. ",
        "Sa mu wa la oru yi ja.",
      ],
      [
        "Lälä oni koja lo:",
        "A fi orin yin O,",
        "Jo, má je k' a ri ewu,",
        "Jesu jo f' iso Re so wa,",
        "Si mu wa la oru yi ja.",
      ],
      [
        "S' Olupamo wa Baba, ",
        "N' tori Iwo l'o mo",
        "Gege b' ewu ti po to",
        "Ti a o ba pade,",
        "Jesu Olufe, gbo ti wa.",
        "Si mu wa la gbogbo won ja.",
      ],
    ], versesEnglish: [
      [
        "THE day is past and over;",
        "All thanks, O Lord to Thee;",
        "We pray Thee now that sinless",
        "The hours of dark may be:",
        "O Jesus keep us in Thy sight,",
        "And guard us through the coming night.",
      ],
      [
        "The joys of day are over;",
        "We lift our hearts to Thee",
        "And ask Thee that offenceless",
        "The hours of dark may be:",
        "O Jesus, make their darkness light",
        "And guard us through the coming night.",
      ],
      [
        "The toils of day are over;",
        "We raise our hymn to Thee,",
        "And ask that free from peril",
        "The hours of dark may be:",
        "O Jesus, keep us in Thy sight,",
        "And guard us through the coming night.",
      ],
      [
        "Be Thou our soul’s preserver,",
        "For Thou, O God, dost know",
        "How many are the perils",
        "Awaiting us below:",
        "O loving Jesus, hear our call",
        "And guard and save us from them all.",
      ],
    ]),
    Hymn(id: '23', versesYoruba: [
      [
        "Ooro didan ti rekoja",
        "Wawa l' akoko na fo lo; ",
        "Bi osan si ti nkoja lo",
        "N' ilę nşu bo.",
      ],
      [
        "Kukuru l' ojo aiye wa,",
        "Were l'osan re nde opin,",
        "Krist', 'Wo ti se ona iye,",
        "Sin wa de 'le.",
      ],
      [
        "Jo fi ore-ofę Rę nla ",
        "Gba okan wa b' ilu t'orun",
        "Je k'a mã wo le didan ni",
        "Ti mbę loke",
      ],
      [
        "Nibi 'molę, iye, ayo,",
        "At' alafia gbe njoba,",
        "T'awon angel ko dekun ko",
        "Orin iyin:",
      ],
      [
        "T'awon mimo wo 'so àlà,",
        "Ti okunkun alę k' şu ",
        "Ti 'Wo Mole aiyeraiye",
        "Je Oluwa.",
      ]
    ], versesEnglish: [
      [
        "The radiant morn hath passed away,",
        "And spent too soon her golden store;",
        "The shadows of departing day,",
        "Creep on once more.",
      ],
      [
        "Our life is but an autumn day,",
        "Its glorious noon how quickly past;",
        "Lead us, O Christ, Thou living way",
        "Safe home at last.",
      ],
      [
        "O by Thy soul-inspiring grace",
        "Uplift our hearts to realms on high;",
        "Help us to look to that bright place",
        "Beyond the sky;",
      ],
      [
        "Where light and life and joy and peace",
        "In undivided empire reign,",
        "And thronging angels never cease",
        "Their deathless strain: ",
      ],
      [
        "Where saints are clothed in spotless white,",
        "And evening shadows never fall",
        "Where thou, eternal Light of light,",
        "Art Lord of all.",
      ]
    ]),
    Hymn(id: '24', versesYoruba: [
      [
        "Ki nto sun, fun oore t' oni",
        "T' Olorun",
        "Şe fun mi.",
        "Ngo yin Olugbala.",
      ],
      ["Oluwa, kini ngo fi yin", "Ooko Rę", "T'O kun fun", "Anu ati ore."],
      [
        "Iwo ti s'eto irin mi",
        "L'ona Rę,",
        "'Wo gb' ebę,",
        "'Wo si gba işe mi.",
      ],
      [
        "Mã ko mi, mã fę mi, titi:",
        "F'alafia,",
        "Rę fun mi",
        "Titi 'Wo y'o pe mi.",
      ],
      [
        "'Wo apata at' odi mi",
        "F' ipa Rę",
        "Pa mi mo",
        "'Gba m' ba dubulę sun.",
      ],
      [
        "Nigbakugba ti mo ba sun",
        "Ję k' emi",
        "Ji dide",
        "Pelu awon mimo.",
      ],
    ], versesEnglish: [
      [
        "ERE I sleep, for every favour",
        "This day showed",
        "By my God,",
        "I will bless my Saviour.",
      ],
      [
        "O my Lord what shall I render",
        "To Thy name,",
        "Still the same",
        "Merciful and tender?",
      ],
      [
        "Thou hast ordered all my goings",
        "In Thy way,",
        "Heard me pray,",
        "Sanctified my doings.",
      ],
      [
        "Leave me not, nut ever love me.",
        "Let Thy peace",
        "Be my bliss,",
        "Till Thou hence remove me.",
      ],
      [
        "Thou my rock, my guard, my tower,",
        "Safely keep,",
        "While I sleep,",
        "Me, with all Thy power.",
      ],
      [
        "So, whene’er in death I slumber, ",
        "Let me rise",
        "With the wise,",
        "Counted in their number.",
      ],
    ]),
    Hymn(
      id: '25',
      versesYoruba: [
        [
          "Oluwa t' O mu Israel la okun ja,",
          "Ti O si gba won kuro li oko eru,",
          "Ti O rojo onje sile lati orun,",
          "On ni mo ngbadura si.",
        ],
        [
          "Olorun t' O gba Danieli lowo Kiniun,",
          "T' O si yo awon meta n'nu ina l' eru,",
          "Eniti awon irawo ngba Tire gbo,",
          "On ni mo ngbadura si.",
        ],
        [
          "Olorun t' O f' oro Re d' afefe duro,",
          "T' o si nso 'banuje oni d' ayo l'ola,",
          "Eniti O yi okuta 'boji kuro,",
          "On ni mo ngbadura si.",
        ],
        [
          "Olorun t' O wo itanna igbe l' aso",
          "Eniti O si mu omi san l' aginju,",
          "Ti O we elese mo ninu eri re,",
          "On ni mo ngbadura si.",
        ],
      ],
      chorusYoruba: [
        "Okanna loni, okanna loni,",
        "B' akoko t' O sin Israeli la okun:",
        "Omo Re ni mo je, 'tori oro Re so,",
        "Pe okanna ni Olorun Iyanu loni.",
      ],
      versesEnglish: [
        [
          "The God who led His people ",
          "Thro’ the parted sea,",
          "And from Egyptian bondage,",
          "Set His children free;",
          "Who rain’d down bread from heaven",
          "All the pilgrim way;",
          "Is the God to whom I pray",
        ],
        [
          "The God who rescued Daniel",
          "From the lion’s den,",
          "And from the fiery furnace,",
          "Sav’d the three young men",
          "Who speak, and constellation",
          "Will His Voice obey,",
          "Is the God to who I pray.",
        ],
        [
          "The God who stills the tempest",
          "With a word divine,",
          "And on the clouds of sorrow",
          "Makes his rainbows shine",
          "Who from the tomb of Jesus,",
          "Rolled the stone away,",
          "Is the God to whom I pray",
        ],
        [
          "The God who clothes the lily",
          "In its robe of snow,",
          "Who in the barren desert",
          "Makes His rivers flow;",
          "The God who lifts the sinner",
          "From the miry clay",
          "Is the God to whom I pray.",
        ],
      ],
      chorusEnglish: [
        "Just the same today,",
        "Just the same today",
        "As when He led His people thro’the sea;",
        "His trustful child I’ll be,",
        "For in His word I see,",
        "The God who doeth wonders,",
        "Is just the same today.",
      ],
    )
  ];
}
