import 'package:church/model/formerModels/hymn.dart';

class HymnText201to300 {
  final hymtext = <Hymn>[
    Hymn(
      id: '201',
      verses: [
        [
          "Ijoye kan to Jesu wa li ale,",
          "Lati bere ona 'gbala on 'mole:",
          "Olukoni dahun l'oro ooto pe",
          "A ò le s' altun nyin bi.",
        ],
        [
          "Enyin omo enia, e gbo oro",
          "Ti Jesu Oluwa so pelu edun:",
          "Mase je k'oro na bo sasan fun nyin,",
          "Ao le s'aitun nyin bi",
        ],
        [
          "Enyin t'e nfe dé 'bi 'simi ogo yi",
          "Lati ba awon mimo korin 'bukun",
          "Bi e ba fe gba iye ainipekun.",
          "Ao le s' aitun nyin bi",
        ],
        [
          "Olufe t'okan rè nsaferi jojo",
          "Le ma w'ona re ni bode orun:",
          "Nje fetisi ohun jeje yi,",
          "Ao le s' aitun nyin bi",
        ],
      ],
      isChorus: true,
      chorus: [
        "A o le s'aitun nyin bi",
        "A o le s'aitun nyin bi",
        "Otito li oro na ti mo so pe,",
        "Ao le s' aitun nyin bi",
      ],
    ),
    Hymn(
      id: '202',
      verses: [
        [
          "Awa pejo l'Oruko Re",
          "Ran isoji Re si wa;",
          "Je ki ojo ibukun ro,",
          "Gege bi lleri Re.",
        ],
        [
          "Je ki ojo Ibukun Rę",
          "Ro si inu okan wa:",
          "A wolę nib'ite aanu.",
          "A ro mo ileri Re.",
        ],
        [
          "\"Ojo ibukun y'o si ro\".",
          "Ileri na ko le ye:",
          "\"Wo ko le sai gbo ebe wa,",
          "B'a ti nf' igbagbo bere.",
        ],
        [
          "Ojo bukun l'awa nfe.",
          "Ojo lati oke wa",
          "Ojo bukun, ran si wa",
          "Iwo l'a o f'ogo fun.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Joo, gbo adura wa,",
        "F'eti si aroye wa,",
        "Şi ferese orun sile:",
        "Rojo ibukun loni",
      ],
    ),
    Hymn(
      id: '203',
      verses: [
        [
          "Otun n'ibukun Oluwa.",
          "T'o ndâ lu mi lojojo:",
          "Mimo ni omi igbala,",
          "T'o nfun mi mu lat'oke.",
        ],
        [
          "Otun n'ibukun Oluwa,",
          "Didun ni lojojumo",
          "Lehin işe l'osangangun,",
          "Mo wa simi l'ese Re",
        ],
        [
          "Eeşe ti aare y'o mu mi",
          "Ti ngo si daku l'ona?",
          "O şeleri agbara Re",
          "Fun işe ojo kokan.",
        ],
        [
          "B'işudędę tab' ikuku",
          "Tilę bo awosanma;",
          "Otun n'ibukun Oluwa,",
          "'Gba mo ba gbadura si.",
        ],
      ],
      isChorus: true,
      chorus: [
        "O mba mi gbe lojojumo.",
        "Imole oju Re ntan:",
        "Onfi owo-otun Rè",
        "Gbagbo omije mi nu",
      ],
    ),
    Hymn(
      id: '204',
      verses: [
        [
          "Oluso-agutan kan mbe ti mo fe.",
          "B'o tinbukun mi, enu ko le so:",
          "O t'eje Re sile. O si ku fun mi,",
          "Ki mba le maa gbe n'nu 'fe Re titi",
        ],
        [
          "Opo onje l'o fimbo okan mi,",
          "Sipa odo tutu l'O nto mi si;",
          "Ire at'aanu Re y'o må tele mi,",
          "Ko s'ohun rere ti y'o fa sehin.",
        ],
        [
          "'Gbat'a dan mi wo ki nle şako lo.",
          "O fi owo Re få mi si agbo;",
          "Ninu afonifoji nko ni beru,",
          "Oluso-agutan mi wà pelu mi.",
        ],
        [
          "'Gbat' ise mi l'aiye ba si pari",
          "'Gbana y'o mu mi lo si ile mi;",
          "'Biti ngo maa gbe titi aiyeraiye,",
          "Pel' awon mimo l'eba ese Rè.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ngo tele Jesu ni ojojumo.",
        "Kos'ewu bi Jesu nṣamona mi,",
        "Ninu imole tab'okunkun;",
        "Jesu Oluso-agutan y'o to mi.",
      ],
    ),
    Hymn(
      id: '205',
      verses: [
        [
          "Tan 'mole Re si wa",
          "Loni yi Oluwa;",
          "Fi ara Re han wa",
          "N' nu oro Mimo Re:",
          "Jo m' okan wa gbona,",
          "K'a maa wo oju Re.",
          "K' awon 'mode le ko",
          "Iyanu ore Re.",
        ],
        [
          "Mi si wa Oluwa,",
          "Ina Emi Mimo,",
          "K'a le fi okan kan",
          "Gbe oruko Re ga;",
          "Jo fi eti igbo,",
          "At' okan ironu,",
          "Fun awon ti a nko,",
          "L' ohun nla t' O ti şe.",
        ],
        [
          "Ba ni so, Oluwa,",
          "Ohun to ye k' a so,",
          "Gege bi oro Re,",
          "Ni ki ęko wa je:",
          "Jo fi eti igbo",
          "At' okan tronu,",
          "Fun awon ti a nko,",
          "L' ohun nla t' O ti se.",
        ],
        [
          "Ba ni so, Oluwa,",
          "Ohun to ye k' a so.",
          "Gege bi oro Re,",
          "Ni ki eko wa je",
          "K' awon agutan Re",
          "Lè maa mo ohun Re",
          "Ibit' Onto won si",
          "Ki nwon si lè maa yo.",
        ],
        [
          "Gbe 'nu wa, Oluwa,",
          "K' ife Re je tiwa,",
          "Iwo nikan lao fi",
          "Ipa wa gbogbo sin:",
          "Kiwa wa je eko.",
          "Fun awon omo Re.",
          "K' o si må kede Rę,",
          "Ninu gbogbo okan.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '206',
      verses: [
        [
          "Bibeli iwe iyanu",
          "Ti o nf' ona han araiye",
          "Fitila ti ntan si ona wa",
          "Lat' aiye yi s' oke orun.",
        ],
        [
          "Bibeli, ofin Oluwa,",
          "Ti o kun fun ore-ofe",
          "Ni pipamo re ere nla mbe.",
          "N' nu re l' a ri 'ye ailopin.",
        ],
        [
          "Bibeli, iwo imole",
          "Ti o ntan lati oke wa",
          "Iranwo ti o l' ogo julo",
          "Da 'na ife si okan wa.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Tan, 'wo 'mole at' oke wa",
        "Tan si okunkun aiye yi.",
        "Tan ninu oru 'yemeji",
        "Tit' ooro titun yo fi de.",
      ],
    ),
    Hymn(
      id: '207',
      verses: [
        [
          "B' onje iye fun mi,",
          "Oluwa mi,",
          "B' o ti bu akara",
          "L'eba odo,",
          "Ninu iwe mimo",
          "Ni mo nwa O",
          "Okan mi nfa si O.",
          "Oro lye!",
        ],
        [
          "Wo li on je iye,",
          "Oluwa mi.",
          "Otito oro Re",
          "Ni y' o gba mi.",
          "Jeki nje ninu Re",
          "Ki mba O gbe",
          "Jęki nfe ooto Re",
          "Ife li O!",
        ],
        [
          "Ran Emi Re si mi,",
          "Oluwa mi,",
          "Ki O si la 'ju mi",
          "Ki nle riran;",
          "Otito oro Re",
          "Fi han fun mi",
          "Ki nri O Oluwa,",
          "N'nu iwe Re.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '208',
      verses: [
        [
          "Bibeli mimo t' orun.",
          "Owon işura, t' emi!",
          "Wo ti nwi bi mo ti ri,",
          "'Wo ti nso bi mo ti wà.",
        ],
        [
          "'Wo nko mi, bi mo şina,",
          "'Wo nfi fe Oluwa han:",
          "'Wo l' O si nto ese mi,",
          "'Wo l' O nd 'are, at' ębi",
        ],
        [
          "'Wo ni ma tu wa ninu,",
          "Ninu wahala aiye;",
          "Wo nko ni, nipa 'gbagbo",
          "Pe a le segun iku",
        ],
        [
          "'Wo l' O nso t' ayo ti mbo",
          "At' iparun elese:",
          "Bibeli mimo t' orun.",
          "Owon Işura t'emi.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '209',
      verses: [
        [
          "Jesu, oro Re ye.",
          "O si nto 'sise wa",
          "Enit' o ba gba gbo,",
          "Y'o l'ayo on 'mole.",
        ],
        [
          "Nigb' ota sunmo wa,",
          "Oro Re l' odi wa;",
          "Oro Itunu ni,",
          "Iko igbala ni.",
        ],
        [
          "B' igbi at' okunkun",
          "Tilę bo wa mole:",
          "Mole re y' o to wa,",
          "Y' o si dabo bo wa.",
        ],
        [
          "Tani le so ayo,",
          "T' o le ka isura,",
          "Ti oro Re nfi fun",
          "Okan onirelę.",
        ],
        [
          "Oro aanu, o nfi",
          "'Lera fun alaye;",
          "Oro iye, o nfi",
          "Itunu feni nku",
        ],
        [
          "Awa iba le mo,",
          "Eko ti O nkoni,",
          "Ki a ba le fe O.",
          "K' a si le sunmo O.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '210',
      verses: [
        [
          "Iwo Oro Olorun,",
          "Ọgbọn at' oke wa,",
          "Ootọ ti ki 'yipada,",
          "Imọlẹ aiye wa:",
          "Awa yin Ọ fun 'mọlẹ,",
          "T' inu Iwe mimọ;",
          "Fitila fun ẹsẹ wa,",
          "Ti ntan titi aiye",
        ],
        [
          "Oluwa l' O f' ẹbun yi",
          "Fun Ijọ Rẹ l' aiye;",
          "A ngbe 'mọlẹ na soke",
          "Lati tan y' aiye ka.",
          "Apoti wura n' iṣe,",
          "O kun fun otitọ;",
          "Aworan Kristi si ni,",
          "Ọrọ iye totọ",
        ],
        [
          "O nfẹ lẹlẹ b' asia,",
          "T' a ta loju ogun;",
          "O ntan b' ina alore,",
          "Si okunkun aiye;",
          "Amọna enia ni,",
          "Ni wahala gbogbo.",
          "Nin' arin omi aiye,",
          "O ntọ wa sọdọ Krist",
        ],
        [
          "Olugbala, ṣe 'jọ Rẹ,",
          "Ni fitila wura;",
          "Lati tan imọlẹ Rẹ,",
          "Bi aiye igbani;",
          "Kọ awọn ti o ṣako,",
          "Lati lo 'mọlẹ yi;",
          "Tit' ookun aiye y' o pin,",
          "Ti nwọn o r' oju Rẹ",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '211',
      verses: [
        [
          "Iwe kan wa ti kika Re.",
          "Ko şoro fun enia,",
          "Ogbon ti awon t' o ka nfe.",
          "Ni okan ti o mo.",
        ],
        [
          "Ise gbogbo t' Olorun şe,",
          "L' oke, n' ile, n' nu wa;",
          "Nwon j' okan ninu iwe na,",
          "Lati f' Olorun han.",
        ],
        [
          "Ise gbogbo t' Olorun şe,",
          "Lat' ode orun ni;",
          "Be l' ogo Ijo Olorun,",
          "T' odo Olorun wa",
        ],
        [
          "Iwo ti O je ki a ri",
          "Ohun t' o dara yi;",
          "Fun wa l' okan lati wa O,",
          "K' a ri O nibi gbogbo.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '212',
      verses: [
        [
          "Baba orun, nin' oro Re",
          "Ni ogo ọrun ntan;",
          "Titi lai l' a o ma yin Ọ",
          "Fun Bibeli mimọ",
        ],
        [
          "Ọpọ 'tunu wa ninu rẹ,",
          "Fun ọkan alarẹ;",
          "Gbogbo ọkan ti ongbẹ ngbẹ,",
          "Nri omi iye mu.",
        ],
        [
          "Ninu Rẹ l' alafia wa,",
          "Ti Jesu fifun wa;",
          "Iye ainipẹkun si wa",
          "N' nu Rẹ fun wa gbogbo",
        ],
        [
          "Iba le ma jẹ ayọ mi,",
          "Lati ma ka titi;",
          "Ki mma ri ọgbọn titun kọ,",
          "N' nu rẹ lojojumọ",
        ],
        [
          "Oluwa Olukọ ọrun,",
          "Maṣe jina si mi;",
          "Kọ mi lati fẹ ọrọ Rẹ,",
          "Ki nri Jesu nibẹ",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '213',
      verses: [
        [
          "Bibel' iwe aiyeraiye!",
          "Tani le r' idi re?",
          "Tani le so idide re?",
          "Tani le r' opin re?",
        ],
        [
          "Aşiri Olodumare;",
          "Iko Oba orun;",
          "Idà t' o pa oro iku;",
          "Aworan Olorun.",
        ],
        [
          "Okan ni o larin opo",
          "Iwe aiye 'gbani,",
          "Iwo l' o s' ona igbala",
          "Di mimo f' araiye.",
        ],
        [
          "Işura ti Metalokan,",
          "Oba nla t' O gunwa;",
          "Jo, tumo ara Re fun mi,",
          "Ki nye şiyemeji",
        ],
        [
          "Ki 'm' şi O pelu adura,",
          "Ki 'm' k' eko n'nu rę",
          "Iwo iwe aiyeraiye,",
          "F' ife Jesu han mi.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '214',
      verses: [
        [
          "Ro mo Bibeli bi a gba nkan 'yoku.",
          "Má so 'lana re ti o s'owon nu;",
          "Ihin re nji gbogbo okan ti ntogbe,",
          "Ileri re nso oku d' alaye.",
        ],
        [
          "Ro mo Bibeli! oro 'yebiye yi,",
          "Nfi iye ainipekun f' araiye;",
          "O n'iye lori ju b'ęda ti rò lo",
          "Wa ibukun re nigba t' o le ri.",
        ],
        [
          "Fitila f' eni ti o ti şako lo,",
          "Amona fun odo t' iba şubu:",
          "'Reti elese t' aiye rè ti sonu,",
          "Opa f' agba, Iwe t' o da julo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ro mo Bibeli",
        "Ro mo Bibeli",
        "Ro mo Bibeli",
        "'Mole fese wa.",
      ],
    ),
    Hymn(
      id: '215',
      verses: [
        [
          "\"Wo oro t' o dun julo,",
          "T' o kun fun ileri,",
          "Ati imuse pelu,",
          "Opin ohun 'Jinle.",
          "Nigba ekun at'ayo,",
          "Yemeji at'èrù.",
          "Mo gbo Jesu wipe, wa,",
          "Mo si lo sodo Re",
        ],
        [
          "Okan mi; 'Wo y' o se lo",
          "Kuro lod' Ore yi.",
          "Sa sunmo timo-timo:",
          "Baa gbé titi d' opin,",
          "Ó şe: ailera mi po:",
          "Mo kun f'ese pupo:",
          "N'tor' emi ko le sako,",
          "Lehin mo ba pada.",
        ],
        [
          "Maa mu mi sunmo do Re",
          "Ki \"Wa\" na ba le je",
          "Ohûn ti a fo jeje",
          "Feniti o sunmo O",
          "Mo mbę loke tab' odo,",
          "Lokere, nitost,",
          "Emi o má tele O",
          "'Gba mo ba gbo 'pe,",
        ],
      ],
      isChorus: true,
      chorus: [
        "Wá, wá s'odo Mi;",
        "Wá, wá s'odo Mi;",
        "Alaare t'orun nwò̟.",
        "Wá, wá sodo Mi",
        "Wá, wá sodo Mi",
      ],
    ),
    Hymn(
      id: '216',
      verses: [
        [
          "\"Bukun wakati na ti to,",
          "Jesu, 'gbat' a sunmo O:",
          "Lati gbo oro iyebiye!",
          "Ti nti enu Re jade!",
        ],
        [
          "Pelu wa loni, bukun wa,",
          "K'a má j' olugbo lasan;",
          "Te ooto Re mo wa laiya,",
          "Ti mbę n'nu oro iye.",
        ],
        [
          "Wo wa b'a ti nwa igbala,",
          "Ti a joko l'ese Re:",
          "A nreti ni iparoro,",
          "Lati gb'ohun didun Re",
        ],
        [
          "La wa n'iye, k'O si to wa,",
          "L'alafia l'ona orun;",
          "F'atupa, ooto saju wa,",
          "Ki a ma ba sina lo.",
        ],
        [
          "Se wa l'eni tutu pelę.",
          "K'a maa f'igboiya s'ooto",
          "L'ookun lo, k'a ma ba kose",
          "Ko s'ewu lojojumo.",
        ],
        [
          "F'imole, ife, agbara,",
          "Fun oro Re lat' oke;",
          "K'o maa şişe b'iwukara,",
          "Ni inu wa titi lo.",
        ],
        [
          "Ran wa lowo k'a le jeri",
          "Si otito t'a dimu:",
          "K'a si je k'awon elomi",
          "To adun ooto na wo.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '217',
      verses: [
        [
          "Oluso-aguntan to wa,",
          "Awa fe itoju Re",
          "Fun wa ni ibukun t'a nfe.",
          "Si pese aye fun wa.",
        ],
        [
          "Tire ni wa, fi wa s' orę",
          "Maa şe amona fun wa,",
          "Gba agbo Re lowo ese",
          "Wá wa 'gbat' a ba şina.",
        ],
        [
          "Je k' a tètè wa oju Re:",
          "Je k' a têtè se 'fe Re:",
          "Oluwa at' Olubukun,",
          "Fi 'fe Re kun okan wa.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Jesu mimo: Jesu mimo,",
        "O ra wa, Tire ni wa,",
        "Jesu mimo, Jesu mimo.",
        "Ora wa, Tire ni wa.",
      ],
    ),
    Hymn(
      id: '218',
      verses: [
        [
          "Ore wo l' a ni bi Jesu,",
          "Ti O ru banuję wa;",
          "Anfani wo lo po bayi,",
          "Lati ma gbadura si;",
          "Alafia pupo l' a nsonu,",
          "A si ti je 'rora po.",
          "Tori a ko nfi gbogbo nkan,",
          "S' adura niwaju Re",
        ],
        [
          "Idanwo ha wa fun wa bi?",
          "A ha ni wahala bi?",
          "A ko gbodo so 'reti nu.",
          "Sa gbadura s' Oluwa,",
          "Ko s' olooto pre bi Re",
          "Ti o le ba wa daro:",
          "Jesu ti mo ailera wa,",
          "Sa gbadura s' Oluwa.",
        ],
        [
          "Eru ha nwo wa l' orun bi?",
          "Aniyan ha po fun wa?",
          "Olugbala je aabo wa,",
          "Sa gbadura s' Oluwa;",
          "Awon ore ha så o ti,",
          "Sa gbadura s' Oluwa,",
          "Yo gbe o s' oke l' apa Re",
          "Iwo yo is ni 'tunu.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '219',
      verses: [
        [
          "Maa gbadura;Emi mbebe n'nu re.",
          "Fun gbogbo aini re igbagbogbo.",
        ],
        [
          "Må gbadura; l'abe eru ese.",
          "Adura nri eje Jesu ti nşân.",
        ],
        [
          "Mã gbadura; b'aare tile mu o",
          "Adura ngbe wa s' eba te Baba.",
        ],
        [
          "Maa gbadura; n'nu wahala aiye,",
          "Adura l' o nfun okan n' isimi.",
        ],
        [
          "Ma gbadura; b' ayo ba yi o ka,",
          "Adura nlu harp, o nko rin Angel.",
        ],
        [
          "Má gbadura b' awon t' o feran sun.",
          "Adura mba won mu omi iye.",
        ],
        [
          "Gbogb' ohun aiye y'o b' aiye koja,",
          "Adura wà titi; ma gbadura.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '220',
      verses: [
        [
          "Ninu gbogbo iji ti nja,",
          "Ninu gbogbo igbi 'ponju.",
          "Abo kan mbe, ti o daju:",
          "O wa l' abe itę anu.",
        ],
        [
          "Ibi kan wa ti Jesu nda",
          "Ororo ayo s' ori wa;",
          "O dûn ju ibi gbogbo lo;",
          "Ite anu t' a f' eje won.",
        ],
        [
          "lbi kan wa fun idapo,",
          "Nibi Ore npade ore",
          "Lairi 'ra, nipa igbagbo,",
          "Nwon y' ite-anu kanna ka",
        ],
        [
          "A! nibo ni a ba sá si,",
          "Nigba 'danwo at' iponju?",
          "A ba şe le bori eşu,",
          "B'oşepe ko si 'te-anu?",
        ],
        [
          "A! bi idi l' a fo sibę.",
          "B' enipe aiye ko si mo.",
          "Orun wa pade okan wa",
          "Ogo si bo ite-anu.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '221',
      verses: [
        [
          "Oju-kan mbe ti ki toogbe,",
          "Nigbat' ile ba şu;",
          "Eti kan si mbę ti ki isé.",
          "'Gbati örun ba wo.",
        ],
        [
          "Apa kan mbę, ti kò le rè",
          "'Gba 'pa enia pin;",
          "Ifę kan mbę, ti ko le kü.",
          "'Gba 'fe aiye ba kú.",
        ],
        [
          "Oju na nwo awon Seraf,",
          "Apa nå d' orun mu;",
          "Eti nå kun f' orin iyin",
          "Ifę na ga l'oke.",
        ],
        [
          "Ipa kan l' enia le lò,",
          "Gbat' ipa gbogbo pin;",
          "Lati ri oju at' apa,",
          "Ati ifę nla nã.",
        ],
        [
          "Ipa na ni adura wa,",
          "Ti nlo 'waju ite:",
          "T' o nmi owo t' o s' aiye ro.",
          "Lati mu 'gbala wa.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '222',
      verses: [
        [
          "Olorun, awa fe",
          "lle t' ola Re wa;",
          "Ayo ibugbe Re",
          "Ju gbogbo ayo lo.",
        ],
        [
          "lle adura ni,",
          "Fun awon omo Re:",
          "Jesu, O wa nibę,",
          "Lati gbo ębę wa.",
        ],
        [
          "Awa fe àsè Rę,",
          "Kil' o dun to l' aiye;",
          "Nib' awon olooto,",
          "Nri O nitosi won.",
        ],
        [
          "Awa fę oro Re.",
          "Oro alafia;",
          "T' itunu at' iye,",
          "Oro ayo titi.",
        ],
        [
          "A fę ko 'rin anu,",
          "T' a nri gba l' aiye yi;",
          "Sugbon awa fę mo",
          "Orin ayo t' orun.",
        ],
        [
          "Jesu, Oluwa wa,",
          "Busi 'fe wa nihin;",
          "Mu wa de 'nu ogo,",
          "Lati yin O titi",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '223',
      verses: [
        [
          "Jesu, nib' eni Re pade,",
          "Nibe, nwon r' ite anu Re:",
          "Nibe, nwon wa O, won ri O.",
          "Tbikibi n' ilę owo.",
        ],
        [
          "Ko s' ogiri t'o se o mo.",
          "O ngbe inu onirele",
          "Nwon mu O wa bi nwon ba wa,",
          "'Gba won nlo 'le, nwon mu O lo.",
        ],
        [
          "Olusagutan eni Re,",
          "So aanu Re 'gbani d' otun:",
          "So adun oruko nla Rę",
          "Fun okan ti nwa oju Re",
        ],
        [
          "Je k'a r' ipa adua nihin,",
          "Lati so 'gbagbo di lile,",
          "Lati gbe ife wa s'oke,",
          "Lati gb' orun ka 'waju wa.",
        ],
        [
          "Oluwa, 'Wo wa nitosi,",
          "N' apa Re, de 'ti Re sile:",
          "Şi orun, sokalę kankan,",
          "Se gbogbo okan ni Tire.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '224',
      verses: [
        [
          "Pase 'bukun re, t' oke wa,",
          "Olorun, s' ara Ijo yi:",
          "Fi ife ti Baba wò wa,",
          "Gbat' a f' eru gb' oju s'oke.",
        ],
        [
          "Paşę ibukun Re, Jesu,",
          "K' a le se omo eyin Re",
          "S' oro ipá s' okan gbogbo,",
          "So f' alailera, tele mi.",
        ],
        [
          "Pase 'bukun l' akoko yi,",
          "Emi ooto, kun ibi yi:",
          "F'agbara iwosan Rę kun,",
          "At' ore-ofe isoji.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '225',
      verses: [
        [
          "Mura ebe, okan mi,",
          "Jesu nfe gb'adura re:",
          "O ti pe k' o gbadura,",
          "Nitorina yio gbo.",
        ],
        [
          "Lodo Oba n' iwo mbo,",
          "Wa lopolopo ebe",
          "Be l' ore-ofe Re po.",
          "Ko s' eni ti bere ju",
        ],
        [
          "Mo t'ibi eru bere:",
          "Gba mi ni eru ese!",
          "Ki eje t' O ta sile",
          "We ebi okan mi nu.",
        ],
        [
          "S' odo Re mo wa 'simi",
          "Oluwa, gba aiye mi;",
          "Nibe ni ki O joko,",
          "Maa je Oba okan mi.",
        ],
        [
          "N' irin ajo mi l' aiye,",
          "K' ife Re maa tu mi n'nu;",
          "Bi Ore at' Oluso.",
          "Mu mi dopin irin mi.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '226',
      verses: [
        [
          "Fi ibukun Re ba wa gbe,",
          "Fi ayo kun okan wa;",
          "K' olukuluku mo 'fe Re'",
          "K' a l' ayo n'nu ore Re.",
          "Tu wa lara, tu wa lara,",
          "La aginju aiye ja.",
        ],
        [
          "Ope at' iyin l' a nfun O,",
          "Fun ihinrere ayo;",
          "Je ki eso igbala Re",
          "Po l' okan at' iwa wa.",
          "Ki oju Re, ki oju Re,",
          "Ma ba wa gbe titi lo.",
        ],
        [
          "Nje, nigbat' a ba si pe wa,",
          "Lati f' aiye yi sile,",
          "K' Angeli gbe wa s' orun,",
          "L'ayo ni k'a j'ipe na.",
          "K' a si joba, k' a si joba,",
          "Pelu Kristi titi lai.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '227',
      verses: [
        [
          "Wa, iwo Isun ibukun,",
          "Mu mi ko 'rin ore Re:",
          "Odo anu ti nsan titi,",
          "Bêre orin 'yin kikan,",
          "Oluwa, ko mi l' orin na,",
          "T' ogun orun nko l' oke;",
          "Je ki nrohin Işura na,",
          "Ti ife Olorun mi.",
        ],
        [
          "Nihin l' a ràn mi lowo de,",
          "Mo gbe Ebenezer ro;",
          "Mo nreti nipa 'nu 're Re,",
          "Ki nde 'le l' alafia;",
          "L'alejo ni Jesu wa mi,",
          "'Gba mo sako lo l' agbo,",
          "Lati yo mi ninu egbe,",
          "O f' eje Rè s' etutu.",
        ],
        [
          "Nit' ore-ofe, lojojumo",
          "Ni 'gbese mi si npo si;",
          "K' ore-ofe yi ja ewon",
          "Ti nşe 'dena okan mi,",
          "Ki nṣako sa l' okan mi nfe,",
          "Ki nko Jesu ti mo fe:",
          "Olugbala gba aiya mi,",
          "Muu ye f' agbala orun.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '228',
      verses: [
        [
          "Olugbala, a tun fe f' ohun kan",
          "Yin oruko Re, k'a to tuka lo;",
          "Ni 'pari 'sin, a dide lati yin;",
          "A o si kunle fun ibukun Re.",
        ],
        [
          "F' alafia fun wa, b' a ti nrele,",
          "Je k' a pari ojo yi pelu Re:",
          "Pa aiya wa mo, si so ète wa,",
          "T' a fi pe oruko Re n' ile yi.",
        ],
        [
          "F' alafia fun wa l' oru oni,",
          "So okunkun rè d' imole fun wa:",
          "Ninu ewu, yo awa omo Re",
          "Ookun on 'molę j' okanna fun O.",
        ],
        [
          "F' alafia fun wa loj' aiye wa,",
          "Re wa l'ekun, k' O si gbè wa ni 'ja",
          "'Gbat' O ba si f' opin s' idamu wa,",
          "Pe wa, Baba, s' orun alafia.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '229',
      verses: [
        [
          "Ma koja mi. Olugbala,",
          "Gbo adura mi;",
          "'Gbat' iwo ba np' elomiran.",
          "Máse koja mi!",
        ],
        [
          "N' ite-anu, je k' emi ri",
          "Itura didun;",
          "Teduntedun ni mo wolę,",
          "Joo ran mi lowo.",
        ],
        [
          "N' igbekele itoye Re.",
          "L'emi o w' oju Re",
          "Wo 'banuje okan mi san,",
          "F' ife Re gba mi,",
        ],
        [
          "Wo orisun itunu mi,",
          "Ju 'yè fun mi lo;",
          "Tani mo ni l' aiye l' orun,",
          "Bikose Iwo?",
        ],
      ],
      isChorus: true,
      chorus: [
        "Jesu! Jesu! Gbo adura mi!",
        "Gbat' iwo ba np' elomiran.",
        "Maşe koja mi.",
      ],
    ),
    Hymn(
      id: '230',
      verses: [
        [
          "Mo fi gbogbo okan mi tan",
          "Eni t'o le gb' emi mi la;",
          "Aabo nla ti ki 'ye lailai,",
          "Oro Rę daju.",
        ],
        [
          "Okan mi nso pelu ayo",
          "Ti Eniti ngbe inu mi,",
          "If' Eniti ntel' oro Re",
          "Lati mu duro,",
        ],
        [
          "Jehofa Olorun gba mi.",
          "Lowo 'yemeji at' eru:",
          "Fi gbagbo gbigbona fun mi;",
          "M' okan mi duro.",
        ],
      ],
      isChorus: true,
      chorus: [
        "\"Emi ni Alfa at' Omega,",
        "Ipilese ati opin,",
        "Ti O wa, t' O ti wa",
        "Ti O si mbowa;",
        "Emi ni Alfa at' Omega,",
        "Ipilęsę ati opin,",
        "Olodumare, Olodumare\" l'Oluwa wi",
      ],
    ),
    Hymn(
      id: '231',
      verses: [
        [
          "Sa gbekele l' ojojo.",
          "Gbekele, l' arin 'danwo,",
          "Bi 'gbagbo tile kere,",
          "Gbekele Jesu nikan.",
        ],
        [
          "Emi Re ntán imole,",
          "Si okan okunkun mi,",
          "L' owo Re nko le subu,",
          "Gbekele Jesu nikan.",
        ],
        [
          "B' ona ba mo ngo ko 'rin,",
          "B' o ba di ngo gbadura,",
          "L' arin ewu ngo kepe",
          "Gbękele Jesu nikan.",
        ],
        [
          "Gbekele titi d' opin,",
          "Tit' aiye y'o fi koja,",
          "Ti a o si de nu ogo,",
          "Gbękęle Jesu nikan.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Gbekele ni gbagbogbo.",
        "Gbekele lo jo jumo",
        "Gbekele lonakona,",
        "Gbekele Jesu nikan.",
      ],
    ),
    Hymn(
      id: '232',
      verses: [
        [
          "Igbala kikun ni Olorun se 'leri",
          "F' eniti o ba gba Jesu Omo Re gbo",
        ],
        [
          "Bi ona mi tile kun fun ewu pupo.",
          "Dajudaju Jesu yio mu mi la ja",
        ],
        [
          "Olufe pupo ni mo ni l' ode orun,",
          "Nwon wa ninu ogo, eyi si l' orin won.",
        ],
        [
          "Awon omode duro l' egbe Oba won,",
          "O nrerin si won bi nwon ti nko orin won,",
        ],
        [
          "Woli at' Oba wa ni ipejopo na,",
          "Nwon nko 'rin bi won ti nla 'ta wura koja.",
        ],
        [
          "Awa pelu ni lati ko n'nu orin na,",
          "Oro orin iyin wa titi lai l' eyi",
        ],
      ],
      isChorus: true,
      chorus: [
        "Alleluya! O pari, mo gba Omo gbo",
        "Mo ri 'gbala ninu eje Olugbala;",
        "Alleluya! O pari mo gba Omo gbo.",
        "Mo ri 'gbala ninu eje Olugbala",
      ],
    ),
    Hymn(
      id: '233',
      verses: [
        [
          "Y'o dahun gbogb' adura,",
          "Ileri ati 'fe Re",
          "Ko sa ti yi pada ri.",
          "Ogo ni f' oruko Re",
        ],
        [
          "Y' o dahun gbogb' adura",
          "Ngo ro mo ileri Rè,",
          "Mo mo On kò je da mi,",
          "Ogo ni f' oruko Re",
        ],
        [
          "Y' o dahun gbogb' adura.",
          "Jek' a bere ni 'gbagbo:",
          "Emi Re nran ni lowo.",
          "Ogo ni f' oruko Re",
        ],
        [
          "Y'o dahun gbogb' adura,",
          "Wa s' ibi itę anu;",
          "Ori idanilo ju.",
          "Ogo ni f' oruko Re.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '234',
      verses: [
        [
          "Gbat' a b' Oluwa rin,",
          "N'nu 'mole oro Re!",
          "Ona wa yio ti mole to!",
          "'Gbat' a ba nse 'fe Re",
          "On yio ma ba wa gbe,",
          "Ati awon t' o gbeke won le E.",
        ],
        [
          "Ko s' ohun to le de,",
          "L' oke tabi ni 'le",
          "T' o le ko agbara Re l' oju;",
          "Iyemeji, eru,",
          "Ibanuje, ekun,",
          "Ko le duro, bi a gbekele.",
        ],
        [
          "Ko si wahala mo,",
          "Tabi ibanuje,",
          "O ti san gbogbo 'gbese wonyi;",
          "Ko si arokan mo,",
          "Tabi ifajuro,",
          "Sugbon 'bukun, b' a ba gbekele.",
        ],
        [
          "A ko le f' enu so,",
          "Bi 'fe re ti po to,",
          "Titi ao fi f' ara wa rubo;",
          "Anu ti O nfihan,",
          "At' ayo t' O nfun ni,",
          "Je ti awon ti o gbekele.",
        ],
        [
          "Ni 'dapo pelu Re,",
          "A o joko l' ese Re,",
          "Tabi ki a ma rin pelu Re,",
          "Awa y' o gbo Tire,",
          "A o j' ise t' O ran wa,",
          "Ma beru, sa gbekele nikan.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Sa gbekele,",
        "Ona miran ko si,",
        "Lati l' ayo n'nu Jesu,",
        "Ju pe, k' a gbekele.",
      ],
    ),
    Hymn(
      id: '235',
      verses: [
        [
          "Enikeni ti o ba gba Jesu gbo,",
          "T' o si gba Ise ori agbelebu,",
          "Yio ri igbala kikun gba l' ofe",
          "Tori Kristi l' agbara lati gbala.",
        ],
        [
          "Enikeni t' o ba gba Ihinrere,",
          "T' o si gbekele Eje Re fun wenu;",
          "Y'o ri irapada ti aiyeraiye,",
          "\"Tori O ni agbara lati gbala.",
        ],
        [
          "Enit' o ba ko gbogb' èsè re sile,",
          "Ti o s' okan rè paya f' Oluwa,",
          "Y'o ni igbala pipe nisisiyi",
          "Tori On ti mura tan lati gbala.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Enyin ayan fe, Olugbala npe yin,",
        "Or' ofe ati anu Re je 'yanu:",
        "O ta eje Re sile fun rapada,",
        "On si ni agbara lati gba ni la",
      ],
    ),
    Hymn(
      id: '236',
      verses: [
        [
          "\"Jesu l' Ore to dara julo.",
          "'Gbati 'gbi aiye ba yi lu o.",
          "Y' o wo okan to gb' ogbe.",
          "Y' o si fi agbara fun,",
          "Jesu l' Ore t' o dara julo.",
        ],
        [
          "Ore pataki ni Jesu je.",
          "O f' alafia kun okan mi",
          "Ni 'gbekele apa Re.",
          "Jesu l' Ore t' o dara julo.",
        ],
        [
          "Bi banuje tile de ba mi,",
          "Ti igbi Jordan si nyi lu mi",
          "Emi kò gbodo beru.",
          "Oluwa mbę nitosi;",
          "Jesu l' Ore to dara julo",
        ],
        [
          "'Gbati a ba de 'le wa orun,",
          "Pelu awon t' o ti lo sa ju.",
          "A o ko'rin l' ebute Re",
          "A o si ma yin i titi,",
          "Jesu l' ore t' o dara julo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Jesu l' Ore t' o dara ju.",
        "Jesu l' Ore t' o dara ju.",
        "On ki y'o je k' o subu.",
        "Y' o gbo 'gbati o ba pè",
        "Jesu l' ore t' o dara julo.",
      ],
    ),
    Hymn(
      id: '237',
      verses: [
        [
          "Jesu wipe On li ona,",
          "Emi si fe tele,",
          "Mo mo pe lehin okunkun",
          "Imole yo si de.",
        ],
        [
          "On li Ooto, Ooto y'o si",
          "Je mole ti nto mi",
          "Oko mi y' o koja okun",
          "Sile alafia.",
        ],
        [
          "On ni Iye, ko si iku,",
          "Ti y' o fò mi l' aiya,",
          "Nitori nipa je Re",
          "Mo ngbe 'nu Re titi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "On li ona, Ooto ati iye.",
        "Ko s' ona mi s' odo Baba, af' odo Re:",
        "On Ii ona, Ooto ati Iye.",
        "Ko s' ona mi s odo Baba, af' odo Re.",
      ],
    ),
    Hymn(
      id: '238',
      verses: [
        [
          "Mo gbo Jesu wipe,",
          "\"Agbara re kere",
          "Alaare, sora, gbadua,",
          "Pipe re mbę lodo Mi",
        ],
        [
          "Oluwa, tooto mo mo,",
          "P' agbara Re nikan",
          "Le s' adęte di mimo.",
          "O lè m' okan lile ro.",
        ],
        [
          "'Gbati 'pè kehin ba dun,",
          "T'O npe mi s' odo Re.",
          "Jesu ti san gbogbo re",
          "Em' o ba g'oke orun.",
        ],
        [
          "N'iwaju 'te ngo duro,",
          "N'nu pipe ewa Krist,",
          "Ngo fi ade ogo mi",
          "Le 'le ese Jesu.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Jesu san gbogbo,",
        "'Gbese ti mo Je",
        "Ese ti m' abawon wa",
        "O fo mi fun bi sno.",
      ],
    ),
    Hymn(
      id: '239',
      verses: [
        [
          "Ibi kan wa ti mo feran,",
          "'Gbat' okan mi poruru:",
          "Ki nwà pelu Kristi nikan,",
          "Ti o wipe \"Wa simi\".",
        ],
        [
          "Gbat' eru aiye ba wuwo.",
          "Ti o si teri mi ba,",
          "Ngo lo s' odo Jesu nikan",
          "Tori Ore mi ni On.",
        ],
        [
          "'Gbati eşu nfe lepa mi",
          "Jesu wipe ki nsa wa;",
          "On ni Abo at' Ore mi,",
          "Oj' ohun gbogbo fun mi."
        ],
      ],
      isChorus: true,
      chorus: [
        "Ki nwa pelu Jesu nikan,",
        "Ki ngbohun je je Re pe:",
        "\"Maşe beru b' aiye ko o.",
        "Emi wa pelu re.",
      ],
    ),
    Hymn(
      id: '240',
      verses: [
        [
          "Isegun wa li okan mi,",
          "Nitori Emi ngbe 'nu mi;",
          "Jeki igbi idanwo de,",
          "Jesu mura lati gba mi.",
        ],
        [
          "Bi 'ja tile le t' o si pe.",
          "B' esu tile b' okan mi ja",
          "Sibe mo je alagbara:",
          "L' agbara Jesu ngo segun.",
        ],
        [
          "Mo ni 'segun lori ese",
          "Mo ni 'segun lori 'boji:",
          "A ni iku ko nipa mo.",
          "Halleluyah! Emi ti la.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Isegun! Isegun! 'segun l' okan mi,",
        "Mo ni isegun nla 'tori Jesu gb' okan mi;",
        "Isegun! Isegun! Bi odo sisan;",
        "Mo ni 'segun nla ninu Eje Jesu.",
      ],
    ),
    Hymn(
      id: '241',
      verses: [
        [
          "Gbogb' ohun t' o nfa mi mo f'ile",
          "Nihin ni Kenaan mo ri ayo",
          "Alafia, 'bukun 'yebiye,",
          "Tori mo ngbe Kenaan nisi.",
        ],
        [
          "Mo ngbe lai-lewu, nko je beru,",
          "Olugbala mi wa nitosi:",
          "Gba mo ba pè yio gb' adura mi",
          "Tori mo ngbe Kenaan nisi.",
        ],
        [
          "Mo mu omi kanga alaigbe,",
          "Ni Kenaan ibugbe ifę mi;",
          "Emi o so fun elomiran.",
          "Pe emi ngbe n' ile Kenaan.",
        ],
        [
          "lyin ailopin ni mo mu wa",
          "Fun Jesu Oba Irapada;",
          "Em' o korin opo anu Re",
          "\"Tori mo ngbe Kenaan nisi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Mo ngbe Kenaan nisisiyi",
        "Nib' owara ibukun gbe wa,",
        "Nibi a ni oro opo or' ofe:",
        "Mo ngbe Kenaan nisisiyi.",
      ],
    ),
    Hymn(
      id: '242',
      verses: [
        [
          "Asegun ati ajogun li aje",
          "Nipa eje Kristi a ni isegun",
          "Oluwa mbe fun wa a ki y'o subu",
          "Ko s' ohun t' o le bori agbara re",
        ],
        [
          "A nlo l'oruko Olorun Israel",
          "Lati segun ese at'aisododo",
          "K' ise fun wa sugbon Tire ni iyin",
          "Fun 'gbala ati segun t'a f' eje ra.",
        ],
        [
          "Enit' o ba si segun li a o fifun,",
          "Lati je manna t'o t'orun wa nihin;",
          "L'ohun y'o si gbe imope asegun,",
          "Y'o wo'so funfun y'o si d'ade wura",
        ],
      ],
      isChorus: true,
      chorus: [
        "Asegun ni wa nipa eje Jesu",
        "Baba fun wa ni segun nipa eje Jesu",
        "Eniti a pa f'elese",
        "Sibe o wa O n joba",
        "Awa ju asegun lo",
        "Awa ju asegun lo",
      ],
    ),
    Hymn(
      id: '243',
      verses: [
        [
          "B'aiye ba nfa mi pelu ogo re,",
          "ko s' ewu omo Olorun ni mi,",
          "Owo agbara Re y'o di mi mu:",
          "L' ojo aiye mai gbogbo.",
        ],
        [
          "Emi ko je gbagbe pe lor' igi",
          "Ni Omo Olorun gbe ku fun mi:",
          "Ko le s'aiku lati gb' okan mi la,",
          "Ko tun si ona miran.",
        ],
        [
          "Ngo j'olooto s' Oluwa Oba mi,",
          "Ngo ma ko'rin 'yin si nigbagbogbo;",
          "Mo mo pe nikehin On y'o gba mi,",
          "Lati ma ba gbe titi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Mo l' Ore t' o npese f' aini gbogbo,",
        "Mo n' ile kan l' oke orun giga,",
        "Wo! Nitori idi eyi na ni",
        "Emi se nko Halleluya.",
      ],
    ),
    Hymn(
      id: '244',
      verses: [
        [
          "Ki ngbekele Olugbala.",
          "L' odo Re mo ni 'bukun,",
          "Ki wahala to yi mi ka",
          "Mu mi sunmo odo Re",
        ],
        [
          "Ni 'gbekele ojiji Re",
          "Nigbati orun ko si",
          "B' o ti wu k' oju orun şu,",
          "Ife Re y'o tan'mole.",
        ],
        [
          "Gbekele imole Re lai,",
          "Ko 'yemeji at' eru,",
          "L'ori oke pelu Jesu,",
          "Gbe okan Re s' oke si",
        ],
      ],
      isChorus: true,
      chorus: [
        "Gbekele lojojumo,",
        "Gbekele Jesu titi;",
        "Ohunkohun t' o le de,",
        "Gbekele Jesu nikan.",
      ],
    ),
    Hymn(
      id: '245',
      verses: [
        [
          "Nigbati ona mi ba s'ookun:",
          "Ti ojo ibi ba si de,",
          "Emi nranti ileri yi pe:",
          "On ko je gbagbe Tire.",
        ],
        [
          "Nigbati 'reti gbogbo ba pin.",
          "T' iyemeji at' eru de;",
          "Ngo wa 'simi l' aiya Eniti",
          "Ko le je gbagbe Tire.",
        ],
        [
          "On kò je gbagbe Tire lailai,",
          "O se owon fun mi pupo:",
          "Lati 'gbati O ti sokalę,",
          "Ti O ngbe 'nu okan mi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "On ko je gbagbe Tire.",
        "On ko je gbagbe Tire.",
        "Bi ore sa, On wa nitosi.",
        "On ko je gbagbe Tire.",
      ],
    ),
    Hymn(
      id: '246',
      verses: [
        [
          "Aigbagbo, bila! t'emi l' Oluwa.",
          "On si dide fun igbala mi;",
          "Ki nsa ma gb' adura On o se 'ranwo;",
          "'Gba Krist' wa lodo mi, ifoiya ko si.",
        ],
        [
          "B'ona mi ba su, On l'o sa nto mi,",
          "Ki nsa gboran sa, On o si pese,",
          "Bi iranlowo eda gbogbo saki,",
          "Oro t'enu Re so y'o bori dandan.",
        ],
        [
          "Ife t'O nfi han ko je ki nro pe,",
          "Y' o fi mi sile ninu wahala,",
          "Iranwo ti mo si nri l' ojojumo,",
          "O nki mi laiya pe, emi o la ja.",
        ],
        [
          "Emi o se kun 'tori iponju,",
          "Tabi irora? O ti so tele!",
          "Mo m' oro Re p' awon ajogun 'gbala,",
          "Nwon ko le s' aikoja larin wahala.",
        ],
        [
          "Eda ko le so kikoro ago,",
          "T' Olugbala mu, k' elese le ye;",
          "Aiye Re tile buru ju t' emi lo,",
          "Jesu  ba le jiya, k' emi si ma sa!",
        ],
        [
          "Nje b' ohun gbogbo, ti nsise ire,",
          "Fun awon t'o duro de Oluwa;",
          "B' oni tile koro, sa ko ni pe mo,",
          "Gbana orin 'segun yio ti dun to!",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '247',
      verses: [
        [
          "Jesu l' Olus' aguntan mi,",
          "Öre eni ti ki ye!",
          "Ko s' ewu bi mo je Tire.",
          "T' On si je temi titi",
        ],
        [
          "Nib' odò omi iye nşan,",
          "Nibe l' O nm' okan mi lo:",
          "Nibiti oko tutu nhu,",
          "L' O nf' onje orun bo mi",
        ],
        [
          "Mo ti fi were şako lo.",
          "N' ife O si wa mi ri;",
          "L' ejika Rè l' O gbe mi si.",
          "O f' ayo mu mi wa 'le.",
        ],
        [
          "Nko beru ojiji iku,",
          "B' iwo ba wa l'odo mi;",
          "Ogo Re ati opa Re.",
          "Awon l' o ntu mi ninu.",
        ],
        [
          "Iwo tę tabili fun mi;",
          "'Wo d' ororo s' ori mi;",
          "A! ayo na ha ti po to",
          "Ti nt' odo Re wa ba mi ?",
        ],
        [
          "Be l'ojo aiye mi gbogbo,",
          "Ore Re ki o ye lai",
          "Oluşaguntan, ngo yin O.",
          "Ninu ile Re titi",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '248',
      verses: [
        [
          "L'aifoiya l' apa Jesu,",
          "L'aifoiya l' aiya Re.",
          "L' abe ojij' ife Re,",
          "L' okan mi o simi",
          "Gbol ohun Angeli ni,",
          "Orin won d'eti mi,",
          "Lati papa ogo wa,",
          "Lati okun Jaspi,",
        ],
        [
          "L'aifoiya l' apa Jesu,",
          "Mo bo low' aniyan:",
          "Mo bo lowo idanwo,",
          "Eşe ko n' ipa mo:",
          "Mo bo lowo 'banuję,",
          "Mo bo lowo eru;",
          "Mo bo lowo Idanwo",
          "ko si ibanuje mo",
        ],
        [
          "Jesu, ābo okan mi,",
          "Jesu ti ku fun mi;",
          "Apata aiyeriaye,",
          "L' emi o gbękęle;",
          "Nihin l' emi o duro,",
          "Tit' oru y'o koja;",
          "Titi ngo fi ri 'molę,",
          "Ni ebute ogo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "L'aifoiya l' apa Jesu,",
        "L'aifoiya l' aiya Re",
        "L'abe ojij' ife Re",
        "L'okan mi o simi.",
      ],
    ),
    Hymn(
      id: '249',
      verses: [
        [
          "Alafia, li aiye ese yi?",
          "Eje Jesu nwipe \"Alafia.\"",
        ],
        [
          "Alafia, ninu opo laa-laa?",
          "Lati se Ife Jesu, ni 'simi",
        ],
        [
          "Alafia n'nu igbl 'banuje?",
          "L'aiya Jesu ni 'dakę roro wà.",
        ],
        [
          "Alafia, gb' ara wa wà l' ajo?",
          "Ni 'pamo Jesu, iberu ko si.",
        ],
        [
          "Alafia, b' a kò tile m' ola?",
          "Sugbon a mo pe Jesu wa lailai.",
        ],
        [
          "Alafia, nigb' akoko iku?",
          "Olugbala wa ti segun iku.",
        ],
        [
          "O to 'jakadi aiye ferę pin,",
          "Jesu y'o pe wa s' orun alafia.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '250',
      verses: [
        [
          "Igbagbo mi n wo O,",
          "Iwo Odaguntan,",
          "Olugbala,",
          "Jo gbo adura mi",
          "M' ese mi gbogbo lo.",
          "K' emi lat' oni lo",
          "Si je Tire.",
        ],
        [
          "Ki ore-ofę Re",
          "F' ilera f' okan mi,",
          "Mu mi tara,",
          "B' Iwo ti ku fun mi",
          "A! k' ifę mi si O.",
          "K' o ma gbona titi,",
          "B' ina iye.",
        ],
        [
          "'Gba mo rin l' okunkun,",
          "Ninu ibinuję,",
          "Ş' amona mi;",
          "M' okunkun lo loni,",
          "Pa 'banuje mi rę,",
          "Ki nma şako kuro",
          "Li odo Rę.",
        ],
        [
          "Gbati aiye ba lo.",
          "T' odo tutu Jesu,",
          "Nşan lori mi",
          "Jesu, ninu ife.",
          "Mu k' ifoiya mi lo.",
          "Gbe mi d' oke orun,",
          "B' okán t'ara.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '251',
      verses: [
        [
          "Isun kan wa t' o kun f' eje.",
          "To ti 'ha Jesu yo,",
          "Elęsę m' ookun ninu rè",
          "O bo ninu ebi.",
        ],
        [
          "'Gba mo f' igbagbo r' isun na,",
          "Ti nşan fun eje Re",
          "Irapada d' orin fun mi",
          "Ti ngo må ko titi.",
        ],
        [
          "Orin t' o dun ju eyi lo.",
          "Li emi o mã ko:",
          "'Gbati ore-ofe Re ba",
          "Mu mi de odo Re",
        ],
        [
          "Mo gbagbo p' O pese fun mi,",
          "Bi mo tile s'aiye:",
          "Ebun ofe t'a feje ra,",
          "Ati duru wura.",
        ],
        [
          "Duru t' a tow' Olorun se,",
          "Ti ko ni baje lai",
          "Ti ao ma fi yin Baba wa.",
          "Oruko Re nikan.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '252',
      verses: [
        [
          "Ohun ogo re l' a nrohin,",
          "Sion, ti Olorun wa,",
          "Oro enit' a ko lè yè,",
          "Se O ye fun bugbe Re:",
          "L' ori apat' aiyeraye,",
          "Kini le mi 'simi rę",
          "A f' odi 'gbala yi o ka,",
          "K'o le rerin ota re.",
        ],
        [
          "Wo! ipado omi lye,",
          "Nt' ife Olorun sun wa,",
          "O to fun gbogbo omo Re",
          "Eru aini ko si mo:",
          "Tal' o le rè, 'gba odo na",
          "Ba nşan t' o le pongbe re?",
          "Or'-ofe Olodumare",
          "Ki ye lat irandiran.",
        ],
        [
          "Ara Sion alabukun,",
          "T' a f' eje Oluwa we",
          "Jesu ti nwon ti ngbekele,",
          "So won d' oba, Woli Re.",
          "Şişa l' ohun afę aiye,",
          "Pelu ogo asan rè.",
          "Işura tooto at'ayo",
          "Kik' omo Sion l' o 'mo.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '253',
      verses: [
        [
          "Nipa Ife Olugbala,",
          "Ki y'o si nkan:",
          "Oju rere Rè ki pada,",
          "Ki y'o si nkan.",
          "Owon l'eje t' o wo wa san,",
          "Pipe l' edidi or' ofę.",
          "Agbara l' owo t' o gba ni,",
          "Ko le si nkan.",
        ],
        [
          "Bia wa ninu iponju,",
          "Ki y'o si nkan,",
          "Igbala kikun ni tiwa,",
          "Ki y'o si nkan,",
          "Igbękęle Olorun dùn,",
          "Gbigbe inu Kristi l' ere,",
          "Emi si nso wa di mimo.",
          "Ko le si nkan.",
        ],
        [
          "Ọjọ ọla yio dara,",
          "Ki y'o si nkan;",
          "Gbagbo le ko'rin n' iponju,",
          "Ki y'o si nkan.",
          "A gbekele 'fe Baba wa;",
          "Jesu nfun wa l' ohun gbogbo;",
          "Titi Jesu yio fi de,",
          "Ko le si nkan.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '254',
      verses: [
        [
          "Ona ara l' Olorun wa,",
          "Ngba s'ise Re l'aiye,",
          "A nri pase Re lor' okun,",
          "O ngun igbi l'esin.",
        ],
        [
          "Ona Re enikan ko mo,",
          "Awamaridi ni,",
          "O pa ise Ijinle mo,",
          "Oba awon oba.",
        ],
        [
          "Ma beru mo, enyin mimo,",
          "Orun t' o su be ni,",
          "O kun fun anu, y' o r' ojo,",
          "Ibukun s' ori yin.",
        ],
        [
          "Mase da Oluwa l' ejo,",
          "Sugbon gbeke re le;",
          "'Gbati o ro pe O nbinu,",
          "Inu Re dun si o.",
        ],
        [
          "Ise Re fere ye wa na,",
          "Y' o ma han siwaju;",
          "Bi o tile koro l' oni,",
          "O mbo wa dun l'ola.",
        ],
        [
          "Afoju ni alaigbagbo,",
          "Ko mo 'se Olorun,",
          "Olorun ni Olutumo,",
          "Y' o m' ona Re ye ni.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '255',
      verses: [
        [
          "Igbagbo mi duro, l'ori",
          "Ẹjẹ at' ododo Jesu;",
          "Nko jẹ gbẹkẹle ohun kan,",
          "Lẹhin orukọ nla Jesu:",
          "Mo duro le Krist' Apata",
          "Ilẹ miran, iyanrin ni.",
        ],
        [
          "B' ire-ije mi tilẹ gun,",
          "Or'-ọfẹ Rẹ ko yi pada;",
          "B' o ti wu k' iji na le to,",
          "Idakọro mi ko ni yẹ:",
          "Mo duro le Krist' Apata",
          "Ilẹ miran, iyanrin ni.",
        ],
        [
          "Majẹmu ati ẹjẹ Rẹ,",
          "L' em' o rọmọ b' ikunmi de",
          "Gbati ko s' atilẹhin mọ,",
          "O jẹ ireti nla fun mi:",
          "Mo duro le Krist' Apata",
          "Ilẹ miran, iyanrin ni.",
        ],
        [
          "Gbat' ipe kẹhin ba si dun,",
          "A! mba le wa ninu Jesu",
          "Ki nwọ ododo Rẹ nikan,",
          "Ki nduro niwaju itẹ:",
          "Mo duro le Krist' Apata",
          "Ilẹ miran, iyanrin ni.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '256',
      verses: [
        [
          "A ba le n' igbagbo aaye,",
          "B' o ti wu k' ota po;",
          "Igbagbo ti ko je mi'ra",
          "Fun aini at' osi.",
        ],
        [
          "Igbagbo ti ko je r' ahun,",
          "L' abe ibawi Re,",
          "Sugbon ti nsimi l' Olorun,",
          "Nigba ibanuje.",
        ],
        [
          "Igbagbo ti ntan siwaju,",
          "Gbat' iji 'ponju de;",
          "Ti ko si je siyemeji",
          "N'nu wahala gbogbo.",
        ],
        [
          "Igbagbo ti ngb'ona tooro,",
          "Titi emi o pin;",
          "Ti y'o si f' imole orun",
          "Tan akete iku.",
        ],
        [
          "Jesu f'igbagbo yi fun mi;",
          "Nje; b' o ti wu ko ri,",
          "Lat' aiye yi lo ngo l' ayo,",
          "Ilu orun rere.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '257',
      verses: [
        [
          "O da mi l'oju! mo ni Jesu,",
          "Itowo adun orun l' eyi je;",
          "Mo di ajogun igbala nla,",
          "Eje Re wę mi, a tun mi bi",
        ],
        [
          "Ngo teriba fun tayotayo,",
          "Mo le ri iran ogo bibo Rè;",
          "Angeli nmu ihin didun wa,",
          "Ti ife at' anu Rè si mi",
        ],
        [
          "Ngo teriba fun, ngo simi le;",
          "Mo di ti Jesu mo d' eni 'bukun,",
          "Ngo mă şora, ngo si gbadura;",
          "Ki ore Rè má fi mi silę.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ngo so itan na, ngo ko'rin na,",
        "Ngo yin Olugbala mi titi",
        "Ngo so itan na, ngo k'orin na,",
        "Ngo yin Olugbala mi titi.",
      ],
    ),
    Hymn(
      id: '258',
      verses: [
        [
          "Igbagbo to ri 'leri na,",
          "Ti ko ka 'şoro si,",
          "T' o nwo Olorun nikanşo,",
          "T'o nwipe,\" Ao segun.\"",
        ],
        [
          "A! eyi koja oye mi,",
          "Sugbon nki y'o beru;",
          "Tor' Oluwa ti şe 'leri,",
          "Oro Rę ki tase.",
        ],
        [
          "Igbagbo nla ti ki tase.",
          "Baba, joo fifun mi,",
          "Igbagbo t' o nduro gangan,",
          "Titi y'o fi şegun.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '259',
      verses: [
        [
          "'Gbati 'danwo yi mi ka,",
          "Odo Krist' ni mo nlo,",
          "Ni ookan aiya Re ni",
          "Ibi isadi mi",
          "Mo ş' okan mi paya fun,",
          "O mo gbogb' edun mi",
          "Bi mo ti nso nkan wonyi,",
          "Om' edun mi kuro.",
        ],
        [
          "'Gbati mo kun fun èrù.",
          "Ti mo nsunkun père.",
          "O tan ibanuję mi",
          "O le èrù, mi lo.",
          "O r' ewu to yi mi ka,",
          "Ati ailera mi,",
          "O fun mi l'ohun ijà,",
          "Lati segun ese.",
        ],
        [
          "Ngo sá lo s'odo Jesu,",
          "Nibi t'o wu k'o Je,",
          "Ngo sa maa wa oju Re,",
          "O daju pe ngo ri,",
          "'Banuje ni, tab' ayo?",
          "Ohun t'o wu k'o je",
          "Odo Re sá ni ngo lo",
          "On y'o si to mi wá.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '260',
      verses: [
        [
          "Nipa igbagbo ninu Krist',",
          "Awa bo lowo ese.",
          "Nipa gbigbękę l' oro Re.",
          "Awa bo lowo ębi.",
        ],
        [
          "Ona iye ti rorun to,",
          "K'a gbekele Krist' nikan;",
          "Aro on 1ja re y'o pin,",
          "Bi Iwo ba je gba A.",
        ],
        [
          "Iku Jesu l'o san gbese,",
          "Ki 'şe ara on 'ronu.",
          "O ti ru ebi ese wa",
          "A! fi okan re fun U.",
        ],
        [
          "A nrin nipa 'gbagbo lairi,",
          "Imo yi ti tobi to!",
          "Ona Olorun på l'eyi,",
          "Má gbekele ero re.",
        ],
      ],
      isChorus: true,
      chorus: [
        "A nrin nipa 'gbagbo lairi,",
        "Eyi l'ona Olorun wa,",
        "A nrin nipa 'gbagbo lairi,",
        "A nto Krist' Imolę.",
      ],
    ),
    Hymn(
      id: '261',
      verses: [
        [
          "Ero didun ni t'ese mi,",
          "T'a sin s'abę omi okun;",
          "'Gbati agbara Olorun",
          "Dide fun 'gbala okan mi.",
        ],
        [
          "Won ki y'o tun gb'ogun ti mi,",
          "Tabi yo okan mi lenu;",
          "Tori agbara Olorun",
          "Ni y'o mu idariji wa.",
        ],
        [
          "Kò si wahala t'o le mú",
          "Eşe mi wa si iranti,",
          "Okan mi s'owon loju Re",
          "Y'o d'abo bo nigbagbogbo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Iwo yio ran ese won lo s'ogbun okun,",
        "Ileri Oluwa ni, o si to fun mi,",
        "B'omi okun tile nho pelu bíbù rè;",
        "Y'o rele y'o si gbę, ko le de ọdo mi,",
        "Nitori Olorun nikan l'o kawo igbi",
        "Omi nla ti inu okun.",
      ],
    ),
    Hymn(
      id: '262',
      verses: [
        [
          "Igbala ni, Igbala ni",
          "Awa eleşè nfę;",
          "Nitori ninu buburu",
          "T'a şe l' awa nşegbe.",
        ],
        [
          "Isę owo wa ti a nşe,",
          "O nwi nigbagbogbo",
          "Pe, igbala ko si nibę;",
          "Işę ko le gba ni",
        ],
        [
          "Nibo ni igbala gbe wa?",
          "Fi han mi, fi han mi:",
          "B'o wa loke, bi isalę,",
          "B'o ba mo, wi fun wa.",
        ],
        [
          "Jesu n'işe Olugbala,",
          "Jesu l' Oluwa wa;",
          "Igbala wà li owo Re:",
          "Fun awa elęsę.",
        ],
        [
          "Wa nisisiyi, wa toro,",
          "Ife wa ninu Re:",
          "Enyin ti o buru l' O npè;",
          "E wa gba igbala.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '263',
      verses: [
        [
          "Idapo didun ti nfun 'ni l'ayo,",
          "Mo ngbekele Jesu Oluwa;",
          "Ifaiyabalę at'itelorun,",
          "F'awon to ngbekele Oluwa.",
        ],
        [
          "A! b'o ti dun to lati maa rin lo,",
          "Mo ngbekele Jesu Oluwa:;",
          "Ona na nye mi si lojojumo,",
          "Mo ngbekele Jesu Oluwa.",
        ],
        [
          "Ko si 'beru mo, ko si 'foiya mo,",
          "Mo ngbekele Jesu Oluwa;",
          "Okan mi balę pe mo ni Jesu,",
          "Mo ngbekele Jesu Oluwa.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Mo ngbekele,",
        "Ko s'ewu 'biti Jesu wa;",
        "Mo ngbekele,",
        "Mo ngbekele Jesu Oluwa.",
      ],
    ),
    Hymn(
      id: '264',
      verses: [
        [
          "Ohun gbogbo l'o je sise",
          "Fun enit'o gba Jesu gbo,",
          "Oruko Re nkò kegan mo,",
          "Otito Re ni mo dimu;",
          "Mo gbagbo pe ohun gbogbo",
          "Ni şişe fun mi ninu Kristi!",
        ],
        [
          "Ohun to şoro ju ni pe",
          "Ki eşe parun ninu mi;",
          "Mo mo, ore-ofę njoba,",
          "Gege bi oro Rè ti wi;",
          "Iwo le se ohun gbogbo,",
          "Emi na le ş'ohun gbogbo.",
        ],
        [
          "B'aiye ba kegan Òrò na,",
          "Oro Olorun ko le yè;",
          "Iwo nfo agbara eşe,",
          "O daju pe iwo le şe;",
          "Ko s'ohun t'o şoro fun O,",
          "Şişe l'ohun gbogbo fun mi.",
        ],
        [
          "Şişe l'ohun gbogbo fun O",
          "Fun Krist' agbara Olorun;",
          "Fun mi 'gbati mo d'atunbi,",
          "Ti mo si di edá titun;",
          "Eşe ko le bori mi mo,",
          "Şişe l'ohun gbogbo fun mi.",
        ],
        [
          "Şişe l'ohun gbogbo fun O;",
          "Fun Krist' agbara ninu mi;",
          "Tan ogo imole Rę ka,",
          "Ki nmá wà fun ara mi mó;",
          "Ki nfihan lat' isisiyi,",
          "Şişe l'ohun gbogbo fun mi",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '265',
      verses: [
        [
          "Ma f' ara fun danwo, nitor' ese ni,",
          "Isegun kan y'o tun fun o l' agbara,",
          "Ja bi okunrin si bori 'fekufe,",
          "Sa tejumo Jesu y'o mu o laja.",
        ],
        [
          "Ma k' egbe buburu, ma s' oro ibi,",
          "Mase pe oruko Olorun l'asan;",
          "Je eniti nronu at' olotito;",
          "Sa tejumo Jesu y'o mu o laja.",
        ],
        [
          "Olorun y'o f' ade f' eniti o segun,",
          "A o fi gbagbo segun b' ota nde si wa,",
          "Kristi yio so agbara wa di otun,",
          "Sa tejumo Jesu, y'o mu o laja.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Bere ranwo at' agbara l'odo Olugbala,",
        "O setan fun iranwo, On yio mu o laja.",
      ],
    ),
    Hymn(
      id: '266',
      verses: [
        [
          "Fun mi n' iwa mimo: igbona okan;",
          "Suru ninu iya; arò fun ese:",
          "Igbagbo n' nu Jesu; ki nmo 'toju Re:",
          "Ayo n'nu isin Re; emi adura.",
        ],
        [
          "Fun mi l' okan ope; gbekele Krist';",
          "Itara f' ogo Re: 'reti n'n oro Re:",
          "Ekun fun iya Re; 'rora f' ogbę Re:",
          "Irelę n'nu 'danwo; iyin fun 'ranwo.",
        ],
        [
          "Fun mi n' iwa funfun; fun mi n'işęgun;",
          "'We abawon mi nu; fa 'fe mi s'orun;",
          "Mu mi ye 'joba Rę; ki nwulo fun O;",
          "Ki nj' alabukunfun; ki ndabi Jesu.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '267',
      verses: [
        [
          "Ngo sunm' O, Olorun",
          "Ngo sunmo O;",
          "B'o tile se 'ponju,",
          "L'o mu mi wa",
          "Sibę, orin mi ję.",
          "Ngo sunm' O, Olorun",
          "Ngo sunmo O.",
        ],
        [
          "Ni ona àjò mi,",
          "B' ile ba şu,",
          "Bi okuta si je irori mi;",
          "Sibę nin' ala mi,",
          "Ngo sunm' O, Olorun,",
          "Ngo sunmo O.",
        ],
        [
          "Nibę ję ki nr' ona",
          "T'o lo s' orun;",
          "Gbogb' ohun t' O fun mi",
          "Nin' aanu Re:",
          "Angel' lati pe mi",
          "Sunm' O, Olorun mi,",
          "Ngo sunmo O.",
        ],
        [
          "Nje 'gbati mo ba ji,",
          "Em' o yin O:",
          "Ngo f' akete mi şe,",
          "Betel fun O;",
          "Bę ninu oşi mi,",
          "Ngo sunm' O, Olorun,",
          "Ngo sunmo O.",
        ],
        [
          "'Gba mba fi ayò lọ,",
          "S'oke orun,",
          "T'o ga ju orun lo,",
          "S'oke giga:",
          "Orin mi yio je",
          "Ngo sunm' O, Olorun,",
          "Ngo sunmo O.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '268',
      verses: [
        [
          "Jesu npe wa, l'osan l'oru,",
          "Lärin irumi aiye;",
          "L'ojojumo l' a ngbohun Re",
          "Wipe, 'Kristian, tele Mi",
        ],
        [
          "Awon Aposteli 'gbani,",
          "Ni odo Galili ni'",
          "Nwon ko ile, ona silę,",
          "Gbogbo nwon si nto lehin.",
        ],
        [
          "Jesu npe wa, kuro ninu",
          "Ohun asan aiye yi",
          "Larin afę aiye, O nwi",
          "Pe, \"Kristian e feran Mi.",
        ],
        [
          "Larin ayo at' ekún wa,",
          "Lārin lāla on 'rorun;",
          "Tantan l' O npe l' ohùn rara",
          "Pe \"Kristian, e feran Mi.",
        ],
        [
          "Olugbala nip' ǎnu Re,",
          "Ję ki a gbo ipe Rę;",
          "F' eti gboran fun gbogbo wa,",
          "K' a fe O ju aiye lo.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '269',
      verses: [
        [
          "Iwo l'Ona; odo Re ni",
          "Awa o ma sá bo",
          "Awon t'o nṣaferi Baba,",
          "Yio wa s'odo Re.",
        ],
        [
          "Iwo l'Ooto; Oro Tire;",
          "L'o le f'ogbon fun wa;",
          "Iwo nikan l'o le ko wa,",
          "T'O si le wè okan.",
        ],
        [
          "Iwo n'Iye: iboji Rę;",
          "Fi agbara Re han;",
          "Awon t'o gbękę won le O,",
          "Nwon bo lowo iku.",
        ],
        [
          "Iwo l'Ona, Ooto, Iye",
          "Je k'a mo ona Rę;",
          "K'a mo otito at' iye,",
          "T'ayo rè ko l'opin.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '270',
      verses: [
        [
          "Mo fe okan laini ese,",
          "Lati yin Oluwa;",
          "Okan ti o mo eję Rę,",
          "T' a ta silę l'ofe.",
        ],
        [
          "Okan sûru, t' o si tutu,",
          "Itę Oludande;",
          "Nibi Kristi nikan nsoro.",
          "Ti o nikan njoba.",
        ],
        [
          "Okan 'rèlè ti nsa f'eşe,",
          "To gbagbo, t' o si mo;",
          "T' iku tab' iye kò le yà,",
          "Lodo Krist' ti ngbe 'bę.",
        ],
        [
          "Okan titun patapata,",
          "T' o kun fun fe orun;",
          "Pipe, tito, mimo, rere,",
          "Aworan Re, Jesu!",
        ],
        [
          "Oluwa, f' Iwa Rę fun mi,",
          "Joo sokale kankan;",
          "Ko ooko titun s' aiya mi,",
          "Oruko Rę t' ife.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '271',
      verses: [
        [
          "Jesu, mo gb'agbelebu mi,",
          "Ki nle ma tọ Ọ lẹhin;",
          "Otoṣi at' ẹni ẹgan,",
          "'Wọ l'ohun gbogbo fun mi:",
          "Bi ini mi gbogbo ṣegbe,",
          "Ti ero mi gbogbo pin;",
          "Sibẹ ọlọrọ ni mo jẹ!",
          "Temi ni Krist' at' Ọrun.",
        ],
        [
          "Ẹda le ma wahala mi,",
          "Yo' mu mi sunmọ Ọ ni;",
          "Idanwo aiye le ba mi,",
          "Ọrun o mu 'simi wa.",
          "Ibanujẹ ko le ṣe nkan",
          "B'ifẹ Rẹ ba wa fun mi;",
          "Ayọ ko si le dun mọ mi,",
          "B'Iwọ ko si ninu rẹ.",
        ],
        [
          "Ọkan mi, gba igbala rẹ,",
          "Bori ẹṣẹ at'ẹru.",
          "F'ayọ wa ni ipokipo,",
          "Maa siṣẹ, si ma jiya:",
          "Ro t' Ẹmi t'o wa ninu rẹ;",
          "At' ifẹ Baba si Ọ;",
          "W'Olugbala t'o ku fun ọ;",
          "Ọmọ ọrun, maṣe kun!",
        ],
        [
          "Njẹ kọja lat' ore s' ogo,",
          "N'n' adura on igbagbọ;",
          "Ọjọ ailopin wa fun Ọ,",
          "Baba y'o mu ọ de 'bẹ.",
          "Iṣẹ rẹ laiye fẹrẹ pin,",
          "Ọjọ ajo rẹ mbuṣe,",
          "Ireti y'o pada s' ayọ,",
          "Adura s' orin iyin",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '272',
      verses: [
        [
          "Iwo l'Ona; odo Re ni",
          "Awa o ma sá bo;",
          "Awon t'o nşaferi Baba,",
          "Yio wa s'odo Re.",
        ],
        [
          "Iwo l'Ooto: Oro Tire:",
          "L'o le f'ogbon fun wa;",
          "Iwo nikan l'o le ko wa,",
          "T'O si le wè okan.",
        ],
        [
          "Iwo n'Iye: iboji Rę;",
          "Fi agbara Re han;",
          "Awon t'o gbękę won le O.",
          "Nwon bo lowo iku.",
        ],
        [
          "Iwo l'Ona, Ooto, Iye",
          "Je k'a mo ona Rę;",
          "K'a mo otito at' iye,",
          "T'ayo re ko l'opin.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '273',
      verses: [
        [
          "Mo jowo ara mi f' Oluwa,",
          "Ngo je Tire, Tire nikan;",
          "Eyi ni y'o je adura mi,",
          "Mu ife Re se ninu mi",
        ],
        [
          "O su mi lati maa d'eşe lo,",
          "Eşę ti ba aiye mi je:",
          "Sugbon Iwo ti tan imole,",
          "Iwo l'ōrun ododo mi.",
        ],
        [
          "Ife Re nikan, Oluwa mi,",
          "Lo yi mi ka, to kun 'nu mi;",
          "Alafia bi odo şişan,",
          "Ti de si inu okan mi",
        ],
        [
          "Se mi mo 'nu ife Re titi,",
          "Ki nma şako lodo Rę mo:",
          "Tani le ya temi t'Oluwa?",
          "Ninu ife Rè ngo ma gbe.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Fa mi mora, f'ife Re fa mi,",
        "Ki nsonu s'inu ife Re;",
        "Fa mi mora, f'ife Re fa mi,",
        "Ki nsonu sinu ife Re.",
      ],
    ),
    Hymn(
      id: '274',
      verses: [
        [
          "Bi Kristi' ti da okan mi nde,",
          "Aiye mi ti dabi orun,",
          "L'aarin 'banuję at' aro,",
          "Ayo ni-lati mo Jesu.",
        ],
        [
          "Mo ti nrope orun jinna,",
          "Sugbon nigbati Jesu de,",
          "L' orun ti de 'nu okan mi,",
          "N'ibe ni yo si wa titi.",
        ],
        [
          "Nibo l' a kò le gbe l' aiye",
          "L' or' oke tabi pętelę,",
          "L' ahere tabi agbala,",
          "Ko s' ewu Jesu wa n'ibę.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Halleluya! ayo l' o ję,",
        "Pe mo ti ri 'dariji gba",
        "Ibikibi ti mo ba wa",
        "Ko s' ewu Jesu wa n'ibę.",
      ],
    ),
    Hymn(
      id: '275',
      verses: [
        [
          "Lekan mo j' elese sugbon mo",
          "Ti gba 'dariji l' od' Oluwa,",
          "L' ofę l' a fifun mi, mo si ri,",
          "Pe o npa oro Re mo.",
        ],
        [
          "Mo fi 'relę kunlę l'ęsę Krist'",
          "Mó si mberu 'binu Olorun,",
          "Nigbat' a şi orun ti me ri,",
          "P' a k' oruko mi s'ilę.",
        ],
        [
          "Or' - ofe nikan l' o gba mi la,",
          "Ayo ki l' o de si okan mi;",
          "A ti dariji mi mo si mo,",
          "P' Eje Kristi mu mi pe.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ooko titun t' a ko silę n'n' ogo,",
        "Temi ni, tooto temi,",
        "Awon angeli Mimo nko 'rin na",
        "\"Elese kan wa 'le;",
        "Tor' Ooko titun kan ti a ko n'n' ogo",
        "Temi ni, tooto temi,",
        "Lehin 'dariji eşe orun ni mo nlo",
        "Nko tun şako mo.",
      ],
    ),
    Hymn(
      id: '276',
      verses: [
        [
          "Okan mi nyo ninu Oluwa,",
          "'Tori O ję lye fun mi,",
          "Ohun Rè dùn pupo lati gbo:",
          "Adun ni lati r' oju Rè,",
        ],
        [
          "O ti nwa mi pę ki nto mo O,",
          "'Gbati mo rin jina, s' agbo;",
          "O gbe mi wa s'ile l' apa Rè",
          "Nibiti pápá tutu wa.",
        ],
        [
          "Ire at' anu Rè yi mi ka,",
          "Or' ofę Re nşan bi odo,",
          "Emi Rè ntó, o si nse 'tunu,",
          "O mba mi lo si 'bikibi.",
        ],
        [
          "Emi y'o dabi Rè ni 'jo kan.",
          "Ngo s' eru wuwo mi kalę,",
          "Titi di 'gbana ngo ş' olooto,",
          "Ni şişe òsó f ade Re.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Emi nyo ninu Re",
        "Emi nyo ninu Re",
        "'Gba gbogbo l'o f' ayo kun okan mi",
        "'Tori emi nyo n'nu Rè.",
      ],
    ),
    Hymn(
      id: '277',
      verses: [
        [
          "Lekan mo jina s' Oluwa,",
          "Mo nfi 'wa mi bi I ninu,",
          "Sugbon Jesu ti gba mi",
        ],
        [
          "Ibinu ati irunu,",
          "Ni ewon t' eşu fi de mi;",
          "Jesu ti ja ide na.",
        ],
        [
          "Ifękufę kun okan mi,",
          "Ati igberaga gbogbo",
          "Ina Emi ti jo won.",
        ],
        [
          "Mo bo lowo iręwesi,",
          "Lowo 'ko gbona ko tutu;",
          "E ba mi yin Oluwa.",
        ],
        [
          "Mo nko'rin şã lojojumo",
          "Mo njo, mo si tun nfo s'oke",
          "Nipa agbara Emi.",
        ],
        [
          "Eje 'yebiye wę mi mo,",
          "Omi lye nşan ninu mi,",
          "Igbala mi di kikun.",
        ],
        [
          "Enyin ara at' ore mi,",
          "Tani ko fę igbala yi,",
          "Ofę ni l'odo Jesu.",
        ],
      ],
      isChorus: true,
      chorus: [
        "A! bi y' o ti dun to.",
        "Dun to, dun to, dun to,",
        "A! bi y' o ti dun to;",
        "Ki Jesu maa gbe inu mi.",
      ],
    ),
    Hymn(
      id: '278',
      verses: [
        [
          "Lekan mo wa 'nu ese, Sugbon Jesu gba mi;",
          "'Gbana molę nla lat'orun wa w' okan mi;",
          "O w'okan mi ninu fę ati oruką,",
          "Oro dię pelu Jesu so mi d' otun.",
        ],
        [
          "'Gbakan ona mi şu, 'gbati ko si ayo,",
          "'Gbakan Ironu bori Imolę Ojo na,",
          "Ikuku eşę dide lati bori ayo.",
          "Sugbon oro dię pelu Jesu mu mi yo,",
        ],
        [
          "'Rònu ati 'beru, oju mi lé l'omi,",
          "Sugbon Jesu jorę to nşo igba gbogbo,",
          "Emi y'o gbadura, 'tori O m'ero mi,",
          "Oro dię pelu Jesu mu dara.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Eje ka s'oro dię pelu Jesu",
        "Je k'a so gbogbo 'soro wa'fun;",
        "Y'o si feti si 'gbe wa;",
        "On yio dahun l'okōkan,",
        "'Gbati mo berę si ma gbadura si;",
        "Iwo mo pe 'na adura njo;",
        "Wo nfę oro dię pelu Jesu mu dara.",
      ],
    ),
    Hymn(
      id: '279',
      verses: [
        [
          "L'ekan mo wa n'ide ewon,",
          "Ko s'ominira fun mi;",
          "Sugbon Jesu wa teti si mi;",
          "Ogo f' Olorun mo dominira.",
        ],
        [
          "Mo ngoke oruri l'ojojumo,",
          "Okunkun salo niwaju ini;",
          "A f' ęsę mi mulę loke giga",
          "Ogo f' Olorun mo dominira.",
        ],
        [
          "O dabo fun ohun ti aiye,",
          "Ohun aiye kan ko le dè mi:",
          "Bi mo ti rin lo mo si ngbadura;",
          "Ogo f' Olorun mo dominira.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Mo d'ominira, mo dominira,",
        "O fó agbara eşu fun mi;",
        "Ogo ni fun Jesu O tu mi silę,",
        "Ogo f' Olorun mo dominira.",
      ],
    ),
    Hymn(
      id: '280',
      verses: [
        [
          "E yo n'nu Oluwa e yo,",
          "Enyin t 'okan re se dede;",
          "Enyin t' o ti yan  Oluwa",
          "Le' banuje at'aro lo.",
        ],
        [
          "E yo tori On l' Oluwa!",
          "L'aiye ati l' orun pelu,",
          "Oro Re bor'ohun gbogbo:",
          "O l' agbara lati gbala.",
        ],
        [
          "Gbati e ba nja ija rere,",
          "Ti ota fere bori yin",
          "Ogun Olorun t' e ko ri",
          "Po ju awon ota yin lo.",
        ],
        [
          "B' okunkun tile yi o ka ,",
          "Pelu isudede gbogbo;",
          "Mase je k' okan re damu,",
          "Sa  gbeke l' Oluwa d' opin.",
        ],
        [
          "Eyo n'nu Oluwa e yo,",
          "E ko'rin iyin re kikan;",
          "Fi duru ati ohun ko;",
          "Alleluya ohun goro.",
        ],
      ],
      isChorus: true,
      chorus: [
        "E yo! E yo!",
        "E yo n'nu Oluwa eyo!",
        "E yo! e yo!",
        "E yo n'nu Oluwa e yo!",
      ],
    ),
    Hymn(
      id: '281',
      verses: [
        [
          "Enyin olukore nin' oko;",
          "T' aare ferę mu tan;",
          "E roju duro de Oluwa,",
          "Y'o s' agbara d'otun,",
        ],
        [
          "Nigba aarę ati 'rewesi,",
          "A ngb'okan wa si O;",
          "Lehin t'a gba Olugbala gbo,",
          "Ki l'a o tun beru.",
        ],
        [
          "Eyo! O mba wa gbe l'ojojo",
          "Ani titi d' opin,",
          "W'oke! E si mã tęsiwaju",
          "Y'o fun yin l' agbara.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Awon t' o duro d' Oluwa,",
        "Y'o s' agbara won d' otun,",
        "Won o fi iye fo",
        "Won o fi lye fo bi idi;",
        "Won o sá. won k' y' o kaarę.",
        "Won o rin, ki'o re won",
        "Won o sá, won k' y' o kaare,",
        "Won o rin, ki 'o re won",
        "Won o sá, won k' y'o kaarę",
        "Yo rin, k' y'o rè won.",
      ],
    ),
    Hymn(
      id: '282',
      verses: [
        [
          "Awon t'o gbekele oluwa",
          "Yio bori igbi idanwo;",
          "Nitori ileri yi daju,",
          "\"Ore-ofe mi to fun o\"",
        ],
        [
          "Ileri rere li eyi je,",
          "Fun awon ero mimo l'ona,",
          "Ti eru npa t' o si nwa simi",
          "\"Ore-ofe Mi to fun o\"",
        ],
        [
          "Larin ire ije ti iye,",
          "Bi aare tile mu o subu;",
          "Tun dide,k' o sit e siwaju",
          "\"Ore-ofe Mi to  fun o\"",
        ],
        [
          "Idanwo ati iyemeji,",
          "At'ewu ko le ba mi leru;",
          "Tori mo di ileri yi mu,",
          "\"Ore-ofe Mi to fun o\"",
        ],
      ],
      isChorus: true,
      chorus: [
        "\"Ore-ofe mi to fun o\"",
        "Ore ofe mi to fun o,",
        "Ore-ofe ti ko l'egbe;",
        "\"Ore-ofe Mi to fun o\"",
      ],
    ),
    Hymn(
      id: '283',
      verses: [
        [
          "Gbekele onigbagbo!",
          "Bi 'ja na tilę pę.",
          "Iwo ni y' o sa segun;",
          "Baba y'o ja fun o",
        ],
        [
          "Gbękęle! larin ewu,",
          "'Danwo nla wa n' tosi,",
          "Larin wahala aiye",
          "Yo mã ş'amona rę.",
        ],
        [
          "Jesu to lati gba wa,",
          "Ore tooto l' O je,",
          "Gbękęle, Onigbagbo,",
          "Sa gbekele d' opin.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Sa gbekele!",
        "B' okunkun tilę şu,",
        "Sa gbekele",
        "Ilę ferę mo na.",
      ],
    ),
    Hymn(
      id: '284',
      verses: [
        [
          "B' eru ese re ba nwo o l'orun",
          "Pe Jesu wole okan rę",
          "B' o ndaniyan iso ji okan re",
          "Pe Jesu wole okan rę.",
        ],
        [
          "Bi o ba nwa iwenumo kiri,",
          "Pe Jesu wole okan rę,",
          "Omi 'wenumo ko jina si o",
          "Pe Jesu wole okan rę.",
        ],
        [
          "B' igbi wahala ba ngbe o kiri,",
          "Pe Jesu wole okan rę,",
          "B' afo ba wa ti aiye ko le di,",
          "Pe Jesu wole okan rę.",
        ],
        [
          "Bi ore t' o gbękęle ba da o",
          "Pe Jesu wole okan rę",
          "On nikan ni Olubanidaro,",
          "Pe Jesu wole okan rę.",
        ],
        [
          "B' o nfę ko'rin awon olubukun,",
          "Pe Jesu wole okan rę.",
          "Bi o nfę wo agbala isimi,",
          "Pe Jesu wole okan rę.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Le 'yemeji re sonu,",
        "Ba Oluwa re laja,",
        "Şi okan re paya fun",
        "Pe Jesu wole okan rę.",
      ],
    ),
    Hymn(
      id: '285',
      verses: [
        [
          "N' irumi at' iji aiye,",
          "Mo gbo ohun itunu kan,",
          "Onso si mi l' eti wipe,",
          "Emi ni; maşe beru.",
        ],
        [
          "Emi l'o wę okan rę mo,",
          "Emi l'o mu ki o riran,",
          "Emi n' iye, imolę rę,",
          "Emi ni: maşe beru.'",
        ],
        [
          "Awon igbi omi wonyi",
          "Ti f' agbara won lu Mi ri,",
          "Nwon kò le se o n' ibi mo:",
          "'Emi ni: maşe beru.'",
        ],
        [
          "Mo ti mu ago yi l'ekan,",
          "'Wo kò le mo kikoro rè;",
          "Emi ti mo bi o ti ri,",
          "'Emi ni: maşe beru.\"",
        ],
        [
          " Mo pé, l' or' eni aarun re",
          "Oju mi ko ye l' ara re,",
          "Ibukun mi wa l' ori re,",
          "\"Emi ni: maşe beru.\"",
        ],
        [
          "Gbat' emi re ba pin l' aiye,",
          "T' awon t' orun wa pade re,",
          "'Wo o gb'ohun kan t' o mo, pe",
          "\"Emi ni: maşe beru\"",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '286',
      verses: [
        [
          "F' eru re, f' afefe,",
          "N' ireti má foiya;",
          "Olorun gbo 'mikanlę rę,",
          "Yio gb' ori re ga.",
        ],
        [
          "N' irumi at' iji,",
          "Y' o ş' ona re fefe:",
          "Duro de igba Re: oru",
          "Y' o pin s' ojo ayo.",
        ],
        [
          "Iwo r' ailera wa,",
          "Inu wa n'iwo mo;",
          "Gbe owo t' o rè si oke,",
          "M'ekun ailera le.",
        ],
        [
          "K'a wà, nigbagbogbo,",
          "So oro Rè tantan;",
          "K' a so titi opin y'o de,",
          "Ifę itoju Rę.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '287',
      verses: [
        [
          "Tire titi lai l' awa se,",
          "Oluwa wa orun:",
          "K' ohun at' okan wa wipe,",
          "Amin, beni k' o ri",
        ],
        [
          "'Gbati aiye ba ndun mo ni,",
          "T' o si nfa okan wa;",
          "K' iro yi pe, \"Tire l' awa\"",
          "Lè mă dún l' eti wa.",
        ],
        [
          "'Gbat' eşe pelu etan rè,",
          "Ba fę şe wa n' ibi;",
          "K'iro yi pe, \"Tire l' awa\"",
          "Tu etan eşe ka.",
        ],
        [
          "'Gbati eşu ba ntafa rè,",
          "S' ori ailera wa;",
          "K' iro yi pe, \"Tire l' awa,\"",
          "Má je ki o re wa.",
        ],
        [
          "\"Tire,\" n' igb' a wa l' omode,",
          "\"Tire\" ni 'gb' a nd' àgbà,",
          "\"Tire\" n' igb' a ba d'arugbo,",
          "Ti aiye wa mbuşe.",
        ],
        [
          "\"Tire,\" titi lai l' awa şe,",
          "A f' ara wa fun O:",
          "Titi aiye ainipekun,",
          "Amin, beni k' o ri.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '288',
      verses: [
        [
          "Ko to k' awon mimo beru,",
          "Ki won so 'reti nu;",
          "'Gba nwọn kò reti 'ranwo Re",
          "Olugbala y' o de.",
        ],
        [
          "Nigbati Abram mu obę,",
          "Olorun ni, \"Duro\";",
          "Agbò ti o wa l' ohun ni,",
          "Y' o dipo omo na.",
        ],
        [
          "'Gba Jona ri sinu omi,",
          "Kò rò lati yo mo;",
          "Sugbon Olorun ran eja,",
          "T' o gbe lo s' ebute.",
        ],
        [
          "B' iru ipa at' ife yi",
          "Ti pò l' oro Rè to!",
          "Emi ba mã k' aniyan mi,",
          "Le Oluwa lowo!",
        ],
        [
          "Ę duro de iranwo Re.",
          "B' o tilę pę, Duro,",
          "B' ileri na tilę falę.",
          "Sugbon kò le pę de.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '289',
      verses: [
        [
          "Oluwa, Iji nf e s' oke,",
          "Igbi omi nru s' oke,",
          "Oju orun pelu şu dudu,",
          "'Ranlowo ko si n' tosi",
          "'Wo kò bere bi a şegbe?",
          "Bawo n' Iwo se le sun?",
          "Gbati 'şeju kokan d' eru ba wa,",
          "Pe omi n' iboji wa.",
        ],
        [
          "Oluwa pel' edun emi,",
          "Mo teriba n' ironu,",
          "Inu okan mi ko ni 'simi;",
          "A! ji k' O gba mi, mao bè;",
          "Igbi eşe on 'binuję,",
          "Ti bo okan mi molę;",
          "Mo şegbe; Oluwa, mo şegbe;",
          "A! yara k' o si gba mi.",
        ],
        [
          "Oluwa, èrù ti koja,",
          "Idakęję si ti de;",
          "Orun f' oju han nin' adagun,",
          "Orun si wa l' aiya mi;",
          "Má duro m' Olurapada,",
          "Má fi mi silę mo:",
          "Pel' ayo ngo d' ebute ibukun,",
          "Ngo simi l'ebute na.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Afefe at' igbi yio se 'fe Mi; Dakę ję",
        "Ibaşe ibinu riru okun,",
        "Ibãşe eşu tab' ohunkohun,",
        "Ko si omi t' o le ri oko nã,",
        "Ti Oluwa orun at' aiye wà,",
        "Nwon yio f' inu didun şe 'fe Mi",
        "Dakę Je",
        "Dakę je, Dakę ję,",
        "Nwon yio f' inu didun şe 'fę Mi",
        "Dakę ję.",
      ],
    ),
    Hymn(
      id: '290',
      verses: [
        [
          "\"Enyin ero, nibo l' e nlo,",
          "T'eyin t' opa l'owo nyin?",
          "A nrin ajo mimo kan lo",
          "Nipa aşe Oba wa;",
          "L'ori oke on pętelę",
          "A nlo s' afin Oba rere",
          "A nlo s' afin Oba rere",
          "A nlo s' ilę t' o dara,",
          "A nlo s' afin Oba rere",
          "A nlo s' ile to dara.",
        ],
        [
          "Enyin ero, e so fun ni,",
          "Ti 'reti ti enyin ni,",
          "Aşo mimo, ade ogo,",
          "Ni Jesu y' o fi fun wa;",
          "Omi lye l' a o mã mu;",
          "A o ba Olorun wa gbe",
          "A o ba Olorun wa gbe",
          "N' ile mimo didara,",
          "A o ba Olorun wa gbe",
          "N' ilę mimo didara.",
        ],
        [
          "Ero a lè ba nyin k' egbę",
          "L'ona ajo s' ile na?",
          "Wa mā kalo, wa mā kalo",
          "Wa si ęgbę ero wa.",
          "Wa, ę maşe fi wa silę,",
          "Jesu nduro, o nreti wa",
          "Jesu nduro, o nreti wa,",
          "N' ilę mimo t' o dara",
          "Jesu nduro, O nreti wa,",
          "N' ilę mimo t' o dara.",
        ],
      ],
      isChorus: false,
      chorus: [''],
    ),
    Hymn(
      id: '291',
      verses: [
        [
          "'Gbat' alafia b' odo nsan s' o-kan mi,",
          "Ti Jesu le 'banuję lo;",
          "Ohunkohun to de, eyi l' orin mi,",
          "Pe 'simi didun de s'okan mi.",
        ],
        [
          "Bi eşu fi idanwo pon mi l' oju,",
          "Ohun kan yi da mi l' oju;",
          "Pe Jesu ti dari gbogb' ese mi ji,",
          "O f'eje Re we okan mi mo.",
        ],
        [
          "Gbo gbo ese mi k' işe die n'nu rè",
          "Gbogbo re l' a dariji mi;",
          "A da Krist' l'ębi ko tun s' ebi fun mi",
          "Yin Oluwa, Iwo okan mi.",
        ],
        [
          "Ngo y' ara mi si mimo fun Oluwa,",
          "B'akoko iku tilę de;",
          "Erù kò si mo 'tori 'Wo o mu mi,",
          "Wo inu isimi didun lo.",
        ],
        [
          "Sugbon bibo Re li emi nduro de,",
          "Iwo n' ireti okan mi,",
          "Igbe ariwo Oko 'yawo y'o ta,",
          "Ireti isimi f' okan mi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "O dara... 'okan mi...",
        "O dara, o dara f' okan mi.",
      ],
    ),
    Hymn(
      id: '292',
      verses: [
        [
          "Mo nduro l' ori ileri Krist' Oba,",
          "Eniti a o ma yin titi lailai:",
          "Ogo f' Olorun, emi y'o må ko'rin",
          "Mo nduro l' ori ileri Re",
        ],
        [
          "Mo nduro le ileri ti ko le ye",
          "'Gbat' iji 'yemeji at' eru ba de",
          "Nipa Oro Rè li emi y'o segun.",
          "Mo nduro l' ori ileri Re.",
        ],
        [
          "Ileri Re, la mi l'oju lati ri,",
          "Iwenumo pipe ninu eje Re:",
          "lleri Rę so okan mi d' omnira,",
          "Mo nduro l' ori ileri Rè.",
        ],
        [
          "Mo nduro le ileri Krist' Oluwa,",
          "Ife lo fi so mi po mo ara Re:",
          "Nipa Oro Rè, mo nsegun lojojo",
          "Mo nduro l' ori ileri Rè.",
        ],
        [
          "A nlo si ile wa l'oke,",
          "Je k'a ma tęsiwaju;",
          "Nibę ao korin 'rapada,",
          "Maa tęsiwaju.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Emi nduro...",
        "(Mo nduro de 'leri: Mo nduro de 'leri)",
        "Emi nduro l' ori ileri Oluwa",
        "Emi nduro",
        "Emi nduro l' ori ileri Re.",
      ],
    ),
    Hymn(
      id: '293',
      verses: [
        [
          "Oju Oluwa ko ti mi,",
          "Nko tiju işę Re:",
          "Lati gb'ola oro Rè ga,",
          "At' agbelebu Rè.",
        ],
        [
          "Mo m'oruko Oluwa mi,",
          "On ni mo gbekele;",
          "Ko ni je ki oju ti mi,",
          "Ki nsi so 'reti nu.",
        ],
        [
          "Ileri Rè duro şinşin,",
          "Y'o pa ohun na mo;",
          "Ti mo fi si itoju Rè,",
          "Tia d'ojo kehin.",
        ],
        [
          "'Gbana y'o gba mi sodo Re",
          "Bi mo tile ş'aiye;",
          "Nilu Jerusalem titun,",
          "Y'o fi mi s'ipo mi.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Nibi agbelebu ni mo ko r'imole",
        "Nibę, eru okàn mi si fò lọ;",
        "Nibę nipa igbagbo mo riran,",
        "Nisi, mo wà l'alafia titi.",
      ],
    ),
    Hymn(
      id: '294',
      verses: [
        [
          "Igbagbo mi ri bi 'simi,",
          "Ibi 'simi didun,",
          "Jesu ni mo gbękę mi le,",
          "A saa l'ogbe fun mi.",
        ],
        [
          "O to fun mi pe Jesu ku,",
          "Eru ko ba mi mo;",
          "Pel'eru eşe ni mo wa,",
          "Ko si je ta mi nu.",
        ],
        [
          "Okan mi simi l'oro Re,",
          "Oro t'a ko silę:",
          "Ooko Re la fi ngba wa la,",
          "At'eje Re pelu.",
        ],
        [
          "Jesu Oluwosan ara,",
          "Oluwasan emi.",
          "O f'emi Re lelę fun mi,",
          "O t'eje Re silę.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Nko ni ş'aroye miran mo,",
        "Nko ni wa awawi kan,",
        "Pe Jesu ku fun eşę mi,",
        "Eyi ti to fun mi.",
      ],
    ),
    Hymn(
      id: '295',
      verses: [
        [
          "Mo ti di eni-irapada,",
          "Nipa eje Odagutan,",
          "Anu Re l'o fi ra mi pada;",
          "Mo d'om'Olorun ti ti lai.",
        ],
        [
          "Mo ti di eni irapada,",
          "Ayo mi enu ko le so,",
          "Imolę oju Rè ntan si mi,",
          "Y'o ma ba mi gbe titi lai.",
        ],
        [
          "Mo nronu Olurapada mi,",
          "Mo nronu Rè t'osan t'oru,",
          "Mo nko'rin iyin si laidękun,",
          "Orin ti ifę Rè si mi.",
        ],
        [
          "Lojo kan ngo rii nin'ewa Re",
          "Oba ti inu mi ndun si,",
          "Enit' O nto işise mi lo.",
          "Ati orin mi li oru.",
        ],
        [
          "Ade kan nduro de mi l'ohun,",
          "Nibit' O lo pese aye;",
          "Pel' awon ti a so di pipe",
          "Ao maa ba gbe titi aiye.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Irapada, eje Rè l'o rà mi pada,",
        "Irapada, Mo d'om'Olorun titi lai.",
      ],
    ),
    Hymn(
      id: '296',
      verses: [
        [
          "Ko ye mi b'ore-ofe Re",
          "Ti wa mi l'awari,",
          "B'O ti f'eje Re 'yebiye",
          "Ra aboși b'emi.",
        ],
        [
          "Ko ye mi bi mo şe d'eni",
          "T'o ni 'gbagbo aye,",
          "B'Oro Rè ti nfun okan mi",
          "Ni isimi didun.",
        ],
        [
          "Kò ye mi b' Emi ti nşişe,",
          "T'o nfi ese han mi,",
          "T'o nfi ewa Jesu han wa,",
          "T'o mbusi 'gbagbo wa.",
        ],
        [
          "Nkò mo 'hun t'o le de, nkò mò,",
          "Ibi tabi rere,",
          "Ayo tabi ibanuję,",
          "Ki nto r'Oluwa mi.",
        ],
        [
          "Nkò mo 'gbat' Oluwa y'o de,",
          "L'ooro tabi l'ale;",
          "Beni nkò m'akoko iku,",
          "Ti ao se mi logo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Sugbon mo m'eniti mo gbagbo,",
        "O da mi loju pe o le pa mo",
        "Ohun ti mo fi le E lowo.",
        "Titi di ojo kehin.",
      ],
    ),
    Hymn(
      id: '297',
      verses: [
        [
          "Mo ntesiwaju l'ona na",
          "Mo ngoke si lojojumo;",
          "Mo ngbadura bi mo ti nlo,",
          "Oluwa jo gbe mi soke.",
        ],
        [
          "Ife okan mi k'o duro,",
          "Larin 'yemeji at'eru,",
          "Awon miran le ma gbe 'be",
          "Ibi giga l'okan mi nfe",
        ],
        [
          "Mo fe ki nga ju aiye lo,",
          "B'esu tile ngbogun ti m;",
          "Mo nfi 'gbagbo gbo orin na,",
          "Ti awon mimo nko loke",
        ],
        [
          "Mo fe de'bi giga julo,",
          "Ninu ogo didan julo,",
          "Mo ngbadura ki nle de 'be,",
          "Oluwa,mu mi de 'le na.",
        ],
        [
          "Fa mi lo si ibi giga,",
          "Laisi Re nko ni le de 'be;",
          "Fa mi titi d'oke orun,",
          "Ki nko'rin lat'bi giga.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Oluwa, jo gbe mi soke,",
        "Fa mi lo si ibi giga;",
        "Apata t'o ga ju mi lo,",
        "Oluwa, jo gbe mi soke",
      ],
    ),
    Hymn(
      id: '298',
      verses: [
        [
          "Ki nle tubo mo Jesu si,",
          "Ki ngba ekun or'ofe Re",
          "Ki nmo igbala Rę kikun,",
          "Ki nmo adun ife Rè si",
        ],
        [
          "Ki nle tubo mo Jesu si,",
          "Ki nk'ęko rere lara rè;",
          "Emi Orun jowo ko mi,",
          "Fi iwa ti Jesu wo mi.",
        ],
        [
          "Ki nle tubo mo Jesu si,",
          "Ki temi Tirè n'ïdapo;",
          "Ninu Bibeli ki nlè mo",
          "Ojulowo ifę Baba.",
        ],
        [
          "Ki nle tubo mo Jesu si,",
          "Ki nmo opo işura Rè",
          "Ki ntan ijoba Rè kalę,",
          "Ki nkede ipadabo Re.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ki nle mo Jesu si,",
        "Ki nle mo Jesu si,",
        "Ki nmo igbala Re kikun;",
        "Ki nmo adun ife Re si.",
      ],
    ),
    Hymn(
      id: '299',
      verses: [
        [
          "Iwo ha ngbekele Jesu b' o ti nlo?",
          "O ha şowon ju ti atęhinwa lo?",
          "O ha j'om'ehin Re, ye Oro Re wo?",
          "Y'o fun o l'Emi Rè si lopolopo.",
        ],
        [
          "Fun inu-rere Rè gbe Ooko Re ga,",
          "Olugbala wa t' o n t'orun sokalę;",
          "K'awon ayanfe Rè juba Oro Rè,",
          "Eni rà wa pada nipa eję Rè.",
        ],
        [
          "Wa pelu igbagbo, wa je ipe Re,",
          "Gbogb' ohun t'e ti gba, wa jowo rè fun;",
          "Y'o tewogb' enit'o sa wa sodo Rè,",
          "Y'o dà ibukun Rè lu lopolopo.",
        ],
      ],
      isChorus: true,
      chorus: [
        "Ki nwon le n'iye, li opolopo,",
        "Ki nwon le n'iye iye l'opolopo:",
        "Ki nwon le n'iye li opolopo,",
        "Ki nwon le ni iye li opolopo.",
      ],
    ),
    Hymn(
        id: '300',
        verses: [
          [
            "Lekan mo jinna s'Olorun,",
            "Mo ku ninu ęsę;",
            "Oro Rè fun mi n'imolę,",
            "Kristi ngbe ninu mi.",
          ],
          [
            "B'itanşan imolę oorun,",
            "Ti nmu itanna tàn,",
            "Beni 'molę lye nwole,",
            "Bi Krist' ti ngbe n'nu mi",
          ],
          [
            "Bi eka l'ara ajara,",
            "Beni mo je loni;",
            "Nipa Oro ore-ofę,",
            "Emi Rè ngbe n'nu mi",
          ],
          [
            "Ongbe Rè l'o ngbę okan mi,",
            "Ki nsa le dabi Rę;",
            "Iro yi l'o nmu 'nu mi dun,",
            "Pe Kristi ngbe n'nu mi.",
          ],
        ],
        isChorus: true,
        chorus: [
          "Kristi ngbe n'nu mi,",
          "Kristi ngbe n'nu mi,",
          "Igbala nla l'eyi je,",
          "Pe Kristi ngbe n'nu mi",
        ])
  ];
}
